import { Metadata } from "next";
import KeyManagement from "./index";
function createCopy() {
  return {
    navTitle: "SETTINGS",
    pageHeader: {
      title: "Unified Settings",
      desc: "Manage settings for the current user",
    },
    account: {
      title: "Account Settings",
      email: "Email",
      uid: "User ID",
      firstName: "First Name",
      lastName: "Last Name",
      phoneNum: "",
      companyName: "Company Name",
      country: "Country",
      userName: "",
      password: "Password",
      changeBtn: "Change",
      save: "Save",
      email_reg_error: "The email format is incorrect",
      saveSuccess: "Save account info success",
      saveFailed: "Save account info failed",
    },
    verify: {
      title: "Verify",
    },
    key: {
      title: "Key Management",
      addKey: "Add New Key",
      name: "Key Name",
      key: "API Key",
      expiration: "Expiration Time",
      creation: "Creation Time",
      createdBy: "Created By",
      lastUseAt: "Last Used",
      operation: "Operation",
    },
    keyModal: {
      add: "Add API Key",
      delete: "Delete API key",
      deleteConfirm: "Are you sure to delete this API key?",
      modify: "Modify API Key",
      desc: "Up to 10 keys can be generated per account.",
      keyName: "Key Name",
      inputKeyName: "Input your key name",
      inputAPIKey: "Input your API Key",
      apikey: "API Key",
      cancel: "Cancel",
      confirm: "Confirm",
      add_success: "Add successfully",
      update_success: "Update successfully",
      key_copied: "Key copied",
      delete_success: "Delete successfully",
      permanent_validity: "Permanent validity",
    },
    team: {
      title: "Team",
      email: "Email",
      teamID: "Team ID",
      role: "Role",
      invite: "Invite",
      add: "Add",
      cancel: "Cancel",
      confirm: "Confirm",
      save: "Save",
      cancelConfirm: "Are you sure you want to cancel this invitation?",
      doCancel: "Yes, cancel invitation",
      close: "Close",
      account: "Account",
      members: {
        title: "Members",
        searchPlaceholder: "Search members...",
        joinDate: "Join Date",
        account: "Member",
        memberId: "Member ID",
        remove: "Remove",
        resend: "Resend Email",
        role: "Role",
        status: "Status",
        invite: "Invite Members",
        edit: "Edit",
        cancelInvite: "Cancel Invitation",
        copyInviteLink: "Copy Invite Link",
        copySuccess: "Invite link copied",
        getFailed: "Failed to retrieve team members",
        alias: "Alias",
      },
      status: {
        all: "All Status",
        active: "Active",
        invitePending: "Invite Pending",
        inviteCanceled: "Invite Canceled",
        inviteExpired: "Invite Expired",
        leftTeam: "Left Team",
      },
      roles: {
        all: "All",
        owner: "Owner",
        admin: "Admin",
        developer: "Developer",
        basic: "Basic",
        billing: "Billing",
      },
      editForm: {
        title: "Edit",
        selectRole: "Select a Role",
        desc: 'Assign access permissions to members by selecting roles. The budget for each new member is unlimited by default. If you need to adjust it, please go to the "Budgets" page.',
        roleCards: {
          admin:
            "Can edit all Novita AI settings, make purchases, update billing, manage memberships, and revoke access for other Super Administrators.",
          developer:
            "Can access the full account, except for membership management and billing.",
          basic:
            "Can only access resources they have personally created and cannot view or manage resources created by other team members.",
          billing:
            "Can manage all billing-related functions, including handling payments, reviewing invoices, and managing subscriptions.",
        },
        error: "Failed to update role",
      },
      removeForm: {
        title: "Remove",
        desc: "Are you sure you want to remove this member?",
        success: "Member removed",
        failed: "Failed to remove member",
      },
      resendForm: {
        title: "Resend Invitation",
        desc: "An invitation has already been sent and is still active. Sending another will replace the existing one.",
        success: "Invitation email sent successfully!",
        failed: "Failed to resend invitation",
      },
      cancelForm: {
        title: "Cancel",
        desc: "Are you sure you want to cancel this invitation?",
        success: "Invitation canceled",
        failed: "Failed to cancel invitation",
        no: "No",
        confirm: "Confirm",
      },
      inviteForm: {
        title: "Invite Members",
        desc: "Invite members to your team",
        limit: "One team can have up to {{max_team_member}} members",
        separate: "Separate multiple emails with commas",
        success: "Invitation emails sent successfully!",
        failed: "Invitation failed",
        required: "Please input the emails",
        invalid: "Some of the emails are invalid",
        inviteLinksTitle:
          "Invitation emails have been sent! You can also share these invite links below with your team members directly. And the links will remain accessible in the members list for future reference.",
        inviteLinks: "Invite Links",
        inviteLink: "Invite Link",
      },
      upgrade: {
        title: "Upgrade to a team account to collaborate with others",
        desc: "Invite other users to your team to share access to the account and resources using scoped roles.",
        button: "Upgrade To Team Account",
        benefits: {
          title: "Team Accounts Benefits",
          desc: "Simplify team workflows and enhance productivity with Team Accounts!",
          items: [
            {
              title: "Role-Based Access",
              desc: "Assign permissions tailored to each member's responsibilities.",
            },
            {
              title: "Centralized Billing",
              desc: "Manage all expenses under one account with clear insights.",
            },
            {
              title: "Streamlined Collaboration",
              desc: "Share resources and work on projects together in real time.",
            },
            {
              title: "Resource Isolation",
              desc: "Ensure secure and precise resource allocation.",
            },
          ],
        },
        dialog: {
          title: "Upgrade to Team Account",
          nameLabel: "Team Display name",
          teamNameSuffix: "'s Team",
          desc: "Upon upgrading to a team account, all personal assets will be transferred to the team. Authorized team members will be able to view and manage these assets.",
          warn: "Please carefully consider team invitations as members might have access to your account and resources.",
          terms:
            "By confirming Upgrade, you agree to our {{terms}} and {{privacy}}.",
          upgradeBtn: "Upgrade",
          upgradeFailed: "Upgrade failed",
          needVerify:
            "Real name authentication is not completed, cannot upgrade to team account",
          goVerify: "Go to real name authentication",
        },
      },
      permissionDetails: {
        trigger: "View permission details",
        title: "Permission Details",
        desc: "The following is a detailed description of the permissions of each role for different resources in the team.",
        read: "Read",
        write: "Write",
        pageTitle: "Team Permission Details",
      },
      messages: {
        setTeamNameFailed: "Set team name failed",
        setAliasFailed: "Failed to update alias",
      },
    },
    auditLogs: {
      title: "Audit Logs",
      members: "Members",
      dateRange: "Date Range",
      member: "Member",
      membersFailed: "Failed to fetch team members",
      selectMember: "Select a Member...",
      search: "Search",
      searchPlaceholder: "Search...",
      service: "Service",
      action: "Action",
      timestamp: "Timestamp",
      user: "User",
      resource: "Resource",
      resourceGroup: "Resource Group",
      resourceID: "Resource ID",
      all: "All",
      searchFailed: "Failed to get audit logs",
      actions: {
        create: "Create",
        delete: "Delete",
        update: "Update",
      },
      resources: {
        project: "Project",
        service: "Service",
      },
    },
  };
}
export const metadata: Metadata = {
  title: "Key Management | Novita AI",
};
export default function KeyManagementPage() {
  return <KeyManagement />;
}
