const origin = "https://novita.ai";

export const CANONICAL_URL = {
  HOME: `${origin}`,
  ABOUT: `${origin}/about`,
  ACCOUNT_INFO: `${origin}/account/info`,
  AFFILIATE: `${origin}/affiliate`,
  REFERRAL: `${origin}/referral`,
  BILLING: `${origin}/billing`,
  BLOG: `${origin}/blog`,
  CONSOLE: `${origin}/console`,
  CONTACT: `${origin}/contact`,
  SANDBOX: `${origin}/sandbox`,
  GPUS: `${origin}/gpus`,
  GPU_BAREMETAL: `${origin}/gpu-baremetal`,
  GPU_INSTANCE: `${origin}/gpu-instance`, // Old address, used for traffic mounting
  GPU_INSTANCE_SAVINGS_PLANS: `${origin}/gpu-instance/savingsPlans`,
  PRICING: `${origin}/pricing`,
  LEGAL: `${origin}/legal`,
  LEGAL_PRIVACY_POLICY: `${origin}/legal/privacy-policy`,
  LEGAL_COOKIE_POLICY: `${origin}/legal/cookie-policy`,
  LEGAL_TERMS_OF_SERVICE: `${origin}/legal/terms-of-service`,
  LEGAL_DEDICATED_ENDPOINTS_SLA: `${origin}/legal/dedicated-endpoints-sla`,
  LLAMA3: `${origin}/llama3`,
  MODELS: `${origin}/models`,
  MODELS_LLM: `${origin}/models/llm`,
  MODELS_DETAIL: `${origin}/models/model-detail`,
  MODEL_API: `${origin}/model-api`,
  MODEL_API_API_CATALOGUE: `${origin}/model-api/api-catalogue`,
  MODEL_API_END_OF_SERVICE: `${origin}/models/end-of-service`,
  MODEL_API_IMAGE: `${origin}/model-api/image`,
  MODEL_API_IMAGE_POKEMON: `${origin}/model-api/image/pokemon`,
  MODEL_API_MODEL: `${origin}/model-api/model`,
  MODEL_API_PLAYGROUND: `${origin}/model-api/playground`,
  ORDER: `${origin}/dedicated-endpoint-order`,
  SERVERLESS: `${origin}/serverless`,
  SETTINGS: `${origin}/settings`,
  TEMPLATES: `${origin}/templates`,
  USER_RESET: `${origin}/user/reset`,
  USER_REGISTER: `${origin}/user/register`,
  USER_LOGIN: `${origin}/user/login`,
  TEAM_PERMISSION_DETAILS: `${origin}/team-permission-details`,
};
