import { MediaModel, ModelType } from "@/types/models";
import { calcPrice } from "@/lib/utils/pricing";
import { FUNC_NAME } from "@/app/models/constants/funcs";

// Audio model unit configuration mapping
export const AUDIO_MODEL_UNIT_MAP: Record<FUNC_NAME, string> = {
  [FUNC_NAME.TXT2SPEECH]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_02_HD]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_02_TURBO]: "1M characters",
  [FUNC_NAME.MINIMAX_VOICE_CLONING]: "voice",
  [FUNC_NAME.MINIMAX_SPEECH_2_5_HD_PREVIEW]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_2_5_TURBO_PREVIEW]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_2_6_TURBO]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_2_6_HD]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_2_8_TURBO]: "1M characters",
  [FUNC_NAME.MINIMAX_SPEECH_2_8_HD]: "1M characters",
  [FUNC_NAME.FISH_AUDIO_TEXT_TO_SPEECH]: "1M characters",
  [FUNC_NAME.FISH_AUDIO_VOICE_CLONING]: "voice",
  [FUNC_NAME.GLM_TTS]: "10K characters",
  [FUNC_NAME.GLM_TTS_CLONE]: "voice",
  [FUNC_NAME.GLM_ASR_2512]: "Mt",
  [FUNC_NAME.VOICE_CLONING_INSTANT]: "voice",
  [FUNC_NAME.VOICE_CLONING]: "voice",
} as Record<FUNC_NAME, string>;

// Helper function to get audio model unit
export const getAudioModelUnit = (funcName: FUNC_NAME): string => {
  return AUDIO_MODEL_UNIT_MAP[funcName] || "1M characters";
};

// Helper function to format price with original and discount prices
const getModelPriceWithDiscount = (
  funcName: FUNC_NAME | string,
  params?: any,
  formatPrice?: (price: number | string) => string,
): any => {
  const price = calcPrice(funcName, params);

  // Handle "-" case
  if (typeof price.discountPrice === "string" && price.discountPrice === "-") {
    return ["-"];
  }

  const formatter = formatPrice || ((p) => String(p));
  const discountPrice = formatter(price.discountPrice);
  const originalPrice = formatter(price.originalPrice);

  return price.discountPrice !== price.originalPrice
    ? [discountPrice, originalPrice]
    : [discountPrice];
};

export const getImageModelPrice = (funcName: FUNC_NAME, params?: any): any => {
  return getModelPriceWithDiscount(funcName, params, (price) => {
    if (typeof price === "string" && price === "-") return "-";
    return `$${price}/image`;
  });
};

export const getAudioModelPrice = (funcName: FUNC_NAME, unit?: string): any => {
  const modelUnit = unit || getAudioModelUnit(funcName);
  return getModelPriceWithDiscount(
    funcName,
    {},
    (price) => `$${price} / ${modelUnit}`,
  );
};

export const getVideoModelPrice = (
  funcName: string,
  params: any,
  unit: string = "video",
): any => {
  return getModelPriceWithDiscount(funcName, params, (price) => {
    if (typeof price === "string" && price === "-") return "-";
    return `$${price}/${unit}`;
  });
};

// Helper function to get all media models by ID
export const getMediaModelById = (id: string): MediaModel | undefined => {
  const allModels = [
    ...getImageModelList(),
    ...getAudioModelList(),
    ...getVideoModelList(),
    ...getAISearchModelList(),
  ];
  return allModels.find((model) => model.id === id);
};

// Helper function to get multiple media models by IDs
export const getMediaModelsByIds = (ids: string[]): MediaModel[] => {
  return ids
    .map((id) => getMediaModelById(id))
    .filter((model): model is MediaModel => model !== undefined);
};

export const getAISearchModelList = (): MediaModel[] => [
  {
    id: "exa-search",
    type: ModelType.AISearch,
    name: "EXA",
    displayName: "EXA",
    tags: ["Search"],
    infos: [["$0.007/request"]],
    link: "https://novita.ai/docs/api-reference/model-apis-exa-search",
    path: "/v3/exa/search",
    series: "EXA",
    platform_release_at: "2026-06-12",
  },
  {
    id: "tavily-search",
    type: ModelType.AISearch,
    name: "Tavily",
    displayName: "Tavily",
    tags: ["Search"],
    infos: [["$0.008/request"]],
    link: "https://novita.ai/docs/api-reference/model-apis-tavily-search",
    path: "/v3/tavily/search",
    series: "Tavily",
    platform_release_at: "2026-06-26",
  },
];

export const getImageModelList = (): MediaModel[] => [
  {
    id: "hunyuan-3-0",
    type: ModelType.Images,
    name: "Hunyuan Image 3",
    displayName: "Hunyuan Image 3",
    tags: ["Text to Image"],
    infos: [getImageModelPrice(FUNC_NAME.HUNYUAN_3_0)],
    link: "https://novita.ai/docs/api-reference/model-apis-hunyuan-image-3",
    path: "/v3/async/hunyuan-image-3",
    isNew: true,
    series: "Hunyuan",
  },
  {
    id: "seedream-3-0-t2i",
    type: ModelType.Images,
    name: "Seedream 3.0 Text to Image",
    tags: ["Text to Image"],
    infos: [getImageModelPrice(FUNC_NAME.SEEDREAM_3_0_T2I)],
    link: "https://novita.ai/docs/api-reference/model-apis-seedream-3-0-t2i",
    path: "/v3/seedream-3-0-txt2img",
    series: "Seedream",
  },
  {
    id: "seedream-4-0",
    type: ModelType.Images,
    name: "Seedream 4.0",
    tags: ["Text to Image", "Image to Image"],
    infos: [getImageModelPrice(FUNC_NAME.SEEDREAM_4_0)],
    link: "https://novita.ai/docs/api-reference/model-apis-seedream-4-0",
    path: "/v3/seedream-4.0",
    series: "Seedream",
  },
  // Provided by dynamic config (trimmed-data: seedream-4.5)
  // {
  //   id: "seedream-4-5",
  //   type: ModelType.Images,
  //   name: "Seedream 4.5",
  //   tags: ["Text to Image", "Image to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.SEEDREAM_4_5)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-seedream-4.5",
  //   path: "/v3/seedream-4.5",
  //   series: "Seedream",
  // },
  // Provided by dynamic config (trimmed-data: seedream-5.0-lite)
  // {
  //   id: "seedream-5.0-lite",
  //   type: ModelType.Images,
  //   name: "Seedream 5.0 Lite",
  //   tags: [],
  //   infos: [getImageModelPrice("seedream-5.0-lite" as FUNC_NAME)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-seedream-5.0-lite",
  //   path: "/v3/seedream-5.0-lite",
  //   series: "Seedream",
  // },
  {
    id: "qwen-txt2img",
    type: ModelType.Images,
    name: "Qwen-Image Text to Image",
    tags: ["Text to Image"],
    infos: [getImageModelPrice(FUNC_NAME.QWEN_TXT2IMG)],
    link: "https://novita.ai/docs/api-reference/model-apis-qwen-txt2img",
    path: "/v3/async/qwen-txt2img",
    series: "Qwen",
  },
  {
    id: "qwen-image-edit",
    type: ModelType.Images,
    name: "Qwen-Image Edit",
    tags: ["Image Edit"],
    infos: [getImageModelPrice(FUNC_NAME.QWEN_IMAGE_EDIT)],
    link: "https://novita.ai/docs/api-reference/model-apis-qwen-image-edit",
    path: "/v3/async/qwen-image-edit",
    isNew: true,
    series: "Qwen",
  },
  {
    id: "flux1-kontext-dev",
    type: ModelType.Images,
    name: "Flux.1 Kontext Dev",
    tags: ["Image to Image"],
    infos: [getImageModelPrice(FUNC_NAME.FLUX1_KONTEXT_DEV)],
    link: "https://novita.ai/docs/api-reference/model-apis-flux-1-kontext-dev",
    path: "/v3/async/flux-1-kontext-dev",
    series: "Flux",
  },
  {
    id: "flux1-kontext-pro",
    type: ModelType.Images,
    name: "Flux.1 Kontext Pro",
    tags: ["Image to Image"],
    infos: [getImageModelPrice(FUNC_NAME.FLUX1_KONTEXT_PRO)],
    link: "https://novita.ai/docs/api-reference/model-apis-flux-1-kontext-pro",
    path: "/v3/async/flux-1-kontext-pro",
    series: "Flux",
  },
  {
    id: "flux1-kontext-max",
    type: ModelType.Images,
    name: "Flux.1 Kontext Max",
    tags: ["Image to Image"],
    infos: [getImageModelPrice(FUNC_NAME.FLUX1_KONTEXT_MAX)],
    link: "https://novita.ai/docs/api-reference/model-apis-flux-1-kontext-max",
    path: "/v3/async/flux-1-kontext-max",
    series: "Flux",
  },
  // Provided by dynamic config (trimmed-data: flux-2-dev, flux-2-flex, flux-2-pro)
  // {
  //   id: "flux-2-dev-image-gen",
  //   type: ModelType.Images,
  //   name: "Flux 2 Dev Image Gen",
  //   displayName: "Flux 2 Dev Image Gen",
  //   tags: ["Text to Image", "Image to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.FLUX_2_DEV_TXT_TO_IMG)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-flux-2-dev",
  //   path: "/v3/async/flux-2-dev",
  //   series: "Flux",
  // },
  // {
  //   id: "flux-2-flex-image-gen",
  //   type: ModelType.Images,
  //   name: "Flux 2 Flex Image Gen",
  //   displayName: "Flux 2 Flex Image Gen",
  //   tags: ["Text to Image", "Image to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.FLUX_2_FLEX_TXT_TO_IMG)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-flux-2-flex",
  //   path: "/v3/async/flux-2-flex",
  //   series: "Flux",
  // },
  // {
  //   id: "flux-2-pro-image-gen",
  //   type: ModelType.Images,
  //   name: "Flux 2 Pro Image Gen",
  //   displayName: "Flux 2 Pro Image Gen",
  //   tags: ["Text to Image", "Image to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.FLUX_2_PRO_TXT_TO_IMG)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-flux-2-pro",
  //   path: "/v3/async/flux-2-pro",
  //   series: "Flux",
  // },
  {
    id: "txt2img",
    type: ModelType.Images,
    name: FUNC_NAME.TXT2IMG,
    displayName: "Text to Image",
    tags: ["Text to Image"],
    infos: [
      getImageModelPrice(FUNC_NAME.TXT2IMG, {
        width: 512,
        height: 512,
        steps: 5,
      }),
      "512*512 5steps",
    ],
    link: "/models/image#txt2img",
    path: "/v3/async/txt2img",
    series: "Others",
  },
  {
    id: "img2img",
    type: ModelType.Images,
    name: FUNC_NAME.IMG2IMG,
    displayName: "Image to Image",
    tags: ["Image to Image"],
    infos: [
      getImageModelPrice(FUNC_NAME.IMG2IMG, {
        width: 512,
        height: 512,
        steps: 5,
      }),
      "512*512 5steps",
    ],
    link: "/models/image#img2img",
    path: "/v3/async/img2img",
    series: "Others",
  },
  {
    id: "remove-background",
    type: ModelType.Images,
    name: FUNC_NAME.REMOVE_BACKGROUND,
    displayName: "Remove Background",
    tags: ["Image Edit"],
    infos: [getImageModelPrice(FUNC_NAME.REMOVE_BACKGROUND)],
    link: "/models/image#remove-background",
    path: "/v3/remove-background",
    series: "Others",
  },
  {
    id: "replace-background",
    type: ModelType.Images,
    name: FUNC_NAME.REPLACE_BACKGROUND,
    displayName: "Replace Background",
    tags: ["Image Edit"],
    infos: [getImageModelPrice(FUNC_NAME.REPLACE_BACKGROUND)],
    link: "/models/image#replace-background",
    path: "/v3/replace-background",
    series: "Others",
  },
  {
    id: "remove-text",
    type: ModelType.Images,
    name: FUNC_NAME.REMOVE_TEXT,
    displayName: "Remove Text",
    tags: ["Text Edit"],
    infos: [getImageModelPrice(FUNC_NAME.REMOVE_TEXT)],
    link: "/models/image#remove-text",
    path: "/v3/remove-text",
    series: "Others",
  },
  {
    id: "inpainting",
    type: ModelType.Images,
    name: FUNC_NAME.INPAINTING,
    displayName: "Inpainting",
    tags: ["Image Edit"],
    infos: [
      getImageModelPrice(FUNC_NAME.INPAINTING, {
        width: 512,
        height: 512,
        steps: 5,
      }),
      "512*512 5steps",
    ],
    link: "/models/image#inpainting",
    path: "/v3/async/inpainting",
    series: "Others",
  },
  {
    id: "cleanup",
    type: ModelType.Images,
    name: FUNC_NAME.CLEANUP,
    displayName: "Cleanup",
    tags: ["Image Edit"],
    infos: [getImageModelPrice(FUNC_NAME.CLEANUP)],
    link: "/models/image#cleanup",
    path: "/v3/cleanup",
    series: "Others",
  },
  {
    id: "merge-face",
    type: ModelType.Images,
    name: FUNC_NAME.MERGE_FACE,
    displayName: "Merge Face",
    tags: ["Face Edit"],
    infos: [getImageModelPrice(FUNC_NAME.MERGE_FACE)],
    link: "/models/image#merge-face",
    path: "/v3/merge-face",
    series: "Others",
  },
  // Models below exist in dynamic config trimmed-data, commented to avoid duplicate display
  // {
  //   id: "image-remove-background",
  //   type: ModelType.Images,
  //   name: FUNC_NAME.IMAGE_REMOVE_BACKGROUND,
  //   displayName: "Image Remove Background",
  //   tags: ["Image Edit"],
  //   infos: [getImageModelPrice(FUNC_NAME.IMAGE_REMOVE_BACKGROUND)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-image-remove-background",
  //   path: "/v3/async/image-remove-background",
  //   series: "Others",
  // },
  // {
  //   id: "image-eraser",
  //   type: ModelType.Images,
  //   name: FUNC_NAME.IMAGE_ERASER,
  //   displayName: "Image Eraser",
  //   tags: ["Image Edit"],
  //   infos: [getImageModelPrice(FUNC_NAME.IMAGE_ERASER)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-image-eraser",
  //   path: "/v3/async/image-eraser",
  //   series: "Others",
  // },
  // {
  //   id: "image-upscaler",
  //   type: ModelType.Images,
  //   name: FUNC_NAME.IMAGE_UPSCALER,
  //   displayName: "Image Upscaler",
  //   tags: ["Image Edit"],
  //   infos: [getImageModelPrice(FUNC_NAME.IMAGE_UPSCALER)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-image-upscaler",
  //   path: "/v3/async/image-upscaler",
  //   series: "Others",
  // },
  // Models below exist in dynamic config trimmed-data, commented to avoid duplicate display
  // {
  //   id: "z-image-turbo-lora",
  //   type: ModelType.Images,
  //   name: "Z-Image Turbo LoRA",
  //   displayName: "Z-Image Turbo LoRA",
  //   tags: ["Text to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.Z_IMAGE_TURBO_LORA)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-z-image-turbo-lora",
  //   path: "/v3/async/z-image-turbo-lora",
  //   series: "Z-Image",
  // },
  // {
  //   id: "z-image-turbo",
  //   type: ModelType.Images,
  //   name: "Z-Image Turbo",
  //   displayName: "Z-Image Turbo",
  //   tags: ["Text to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.Z_IMAGE_TURBO)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-z-image-turbo",
  //   path: "/v3/async/z-image-turbo",
  //   series: "Z-Image",
  // },
  // Models below exist in dynamic config trimmed-data, commented to avoid duplicate display
  // {
  //   id: "glm-image",
  //   type: ModelType.Images,
  //   name: "GLM Image Generation",
  //   displayName: "GLM Image Generation",
  //   tags: ["Text to Image"],
  //   infos: [getImageModelPrice(FUNC_NAME.GLM_IMAGE)],
  //   link: "/docs/api-reference/model-apis-glm-image",
  //   path: "/v3/async/glm-image",
  //   series: "GLM",
  // },
];

export const getAudioModelList = (): MediaModel[] => [
  {
    id: "minimax-speech-02-hd",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-02-hd",
    displayName: "MiniMax speech-02-hd",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_02_HD)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-02-hd",
    path: "/v3/async/minimax-speech-02-hd",
    series: "MiniMax",
  },
  {
    id: "minimax-speech-02-turbo",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-02-turbo",
    displayName: "MiniMax speech-02-turbo",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_02_TURBO)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-02-turbo",
    path: "/v3/async/minimax-speech-02-turbo",
    series: "MiniMax",
  },
  {
    id: "minimax-speech-2.5-hd-preview",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-2.5-hd-preview",
    displayName: "MiniMax speech-2.5-hd-preview",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_5_HD_PREVIEW)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.5-hd",
    path: "/v3/async/minimax-speech-2.5-hd",
    series: "MiniMax",
  },

  {
    id: "minimax-speech-2.5-turbo-preview",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-2.5-turbo-preview",
    displayName: "MiniMax speech-2.5-turbo-preview",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_5_TURBO_PREVIEW)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.5-turbo",
    path: "/v3/async/minimax-speech-2.5-turbo",
    series: "MiniMax",
  },
  {
    id: "minimax-speech-2.6-turbo",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-2.6-turbo",
    displayName: "MiniMax speech-2.6-turbo",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_6_TURBO)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.6-turbo",
    path: "/v3/async/minimax-speech-2.6-turbo",
    series: "MiniMax",
  },
  {
    id: "minimax-speech-2.6-hd",
    isNew: true,
    type: ModelType.Audio,
    name: "MiniMax speech-2.6-hd",
    displayName: "MiniMax speech-2.6-hd",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_6_HD)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.6-hd",
    path: "/v3/async/minimax-speech-2.6-hd",
    series: "MiniMax",
  },
  // Provided by dynamic config (trimmed-data: minimax-speech-2.8-turbo, minimax-speech-2.8-hd)
  // {
  //   id: "minimax-speech-2.8-turbo",
  //   isNew: true,
  //   type: ModelType.Audio,
  //   name: "MiniMax speech-2.8-turbo",
  //   displayName: "MiniMax speech-2.8-turbo",
  //   tags: ["Text to Speech"],
  //   infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_8_TURBO)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.8-turbo",
  //   path: "/v3/async/minimax-speech-2.8-turbo",
  //   series: "MiniMax",
  // },
  // {
  //   id: "minimax-speech-2.8-hd",
  //   isNew: true,
  //   type: ModelType.Audio,
  //   name: "MiniMax speech-2.8-hd",
  //   displayName: "MiniMax speech-2.8-hd",
  //   tags: ["Text to Speech"],
  //   infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_8_HD)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.8-hd",
  //   path: "/v3/async/minimax-speech-2.8-hd",
  //   series: "MiniMax",
  // },
  // {
  //   id: "minimax-speech-2.8-turbo-sync",
  //   isNew: true,
  //   type: ModelType.Audio,
  //   name: "MiniMax speech-2.8-turbo",
  //   displayName: "MiniMax Speech 2.8 Turbo Sync Text-to-Speech",
  //   tags: ["Text to Speech"],
  //   infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_8_TURBO)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.8-turbo",
  //   path: "/v3/minimax-speech-2.8-turbo",
  //   series: "MiniMax",
  // },
  // {
  //   id: "minimax-speech-2.8-hd-sync",
  //   isNew: true,
  //   type: ModelType.Audio,
  //   name: "MiniMax Speech 2.8 HD Sync Text-to-Speech",
  //   displayName: "MiniMax speech-2.8-hd",
  //   tags: ["Text to Speech"],
  //   infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_SPEECH_2_8_HD)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-minimax-speech-2.8-hd",
  //   path: "/v3/minimax-speech-2.8-hd",
  //   series: "MiniMax",
  // },
  {
    id: "minimax-voice-cloning",
    type: ModelType.Audio,
    name: "MiniMax Voice-Cloning",
    displayName: "MiniMax Voice-Cloning",
    tags: ["Voice Cloning"],
    infos: [getAudioModelPrice(FUNC_NAME.MINIMAX_VOICE_CLONING)],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-voice-cloning",
    path: "/v3/async/minimax-voice-cloning",
    series: "MiniMax",
  },
  {
    id: "fish-audio-text-to-speech",
    type: ModelType.Audio,
    name: "Fish Audio Text to Speech",
    displayName: "Fish Audio Text to Speech",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.FISH_AUDIO_TEXT_TO_SPEECH)],
    link: "https://novita.ai/docs/api-reference/model-apis-fish-audio-text-to-speech",
    path: "/v3/async/fish-audio-text-to-speech",
    series: "Fish Audio",
  },
  {
    id: "fish-audio-voice-cloning",
    type: ModelType.Audio,
    name: "Fish Audio Voice Cloning",
    displayName: "Fish Audio Voice Cloning",
    tags: ["Voice Cloning"],
    infos: [getAudioModelPrice(FUNC_NAME.FISH_AUDIO_VOICE_CLONING)],
    link: "https://novita.ai/docs/api-reference/model-apis-fish-audio-voice-cloning",
    path: "/v3/async/fish-audio-voice-cloning",
    series: "Fish Audio",
  },
  {
    id: "txt2speech",
    type: ModelType.Audio,
    name: FUNC_NAME.TXT2SPEECH,
    displayName: "Text to Speech",
    tags: ["Text to Speech"],
    infos: [getAudioModelPrice(FUNC_NAME.TXT2SPEECH)],
    link: "https://novita.ai/docs/api-reference/model-apis-text-to-speech#text-to-speech",
    path: "/v3/async/text-to-speech",
    series: "Others",
  },
  // Provided by dynamic config (trimmed-data: glm-tts, glm-tts-clone, glm-asr)
  // {
  //   id: "glm-tts",
  //   type: ModelType.Audio,
  //   name: "GLM TTS",
  //   displayName: "GLM TTS",
  //   tags: ["Text to Speech"],
  //   infos: [getAudioModelPrice(FUNC_NAME.GLM_TTS)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-glm-tts",
  //   path: "/v3/glm-tts",
  //   series: "GLM",
  // },
  // {
  //   id: "glm-tts-clone",
  //   type: ModelType.Audio,
  //   name: "GLM TTS Clone",
  //   displayName: "GLM TTS Clone",
  //   tags: ["Voice Cloning"],
  //   infos: [getAudioModelPrice(FUNC_NAME.GLM_TTS_CLONE)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-glm-tts-voice-clone",
  //   path: "/v3/glm-tts-voice-clone",
  //   series: "GLM",
  // },
  // {
  //   id: "glm-asr-2512",
  //   type: ModelType.Audio,
  //   name: "GLM Audio to Text",
  //   displayName: "GLM Audio to Text",
  //   tags: ["Speech to Text"],
  //   infos: [getAudioModelPrice(FUNC_NAME.GLM_ASR_2512)],
  //   link: "https://novita.ai/docs/api-reference/model-apis-glm-asr",
  //   path: "/v3/glm-asr",
  //   series: "GLM",
  // },
];

export const getVideoModelList = (): MediaModel[] => [
  // Provided by dynamic config (trimmed-data: wan2.6-t2v, wan2.6-i2v, wan2.6-v2v)
  // {
  //   id: "wan-2-6-t2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.6 Text to Video",
  //   displayName: "Wan 2.6 Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_6_T2V, {
  //       model: "WAN2_6_T2V_1080P_5S",
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "/models/image#wan-2.6-t2v",
  //   path: "/v3/async/wan2.6-t2v",
  //   isNew: true,
  //   series: "Wan",
  // },
  // {
  //   id: "wan-2-6-i2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.6 Image to Video",
  //   displayName: "Wan 2.6 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_6_I2V, {
  //       model: "WAN2_6_I2V_1080P_5S",
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "/models/image#wan-2.6-i2v",
  //   path: "/v3/async/wan2.6-i2v",
  //   isNew: true,
  //   series: "Wan",
  // },
  // {
  //   id: "wan-2-6-v2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.6 Reference to Video",
  //   displayName: "Wan 2.6 Reference to Video",
  //   tags: ["Video to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_6_V2V, {
  //       model: "WAN2_6_V2V_1080P_5S",
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "/models/image#wan-2.6-v2v",
  //   path: "/v3/async/wan2.6-v2v",
  //   isNew: true,
  //   series: "Wan",
  // },
  {
    id: "minimax-hailuo-02",
    type: ModelType.Video,
    name: "MiniMax Hailuo 02",
    displayName: "MiniMax Hailuo 02",
    tags: ["Image to Video", "Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.MINIMAX_HAILUO_02, {
        resolutionType: "1080P",
        duration: 6,
      }),
      ["1080P 6s"],
    ],
    link: "/models/image#minimax-hailuo-02",
    path: "/v3/async/minimax-hailuo-02",
    series: "MiniMax",
  },
  {
    id: "minimax-hailuo-2.3-t2v",
    type: ModelType.Video,
    name: "MiniMax Hailuo 2.3 Text to Video",
    displayName: "MiniMax Hailuo 2.3 Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.MINIMAX_HAILUO_2_3_T2V, {
        resolutionType: "1080P",
        duration: 6,
      }),
      ["1080P 6s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-hailuo-2.3-t2v",
    path: "/v3/async/minimax-hailuo-2.3-t2v",
    isNew: true,
    series: "MiniMax",
  },
  {
    id: "minimax-hailuo-2.3-i2v",
    type: ModelType.Video,
    name: "MiniMax Hailuo 2.3 Image to Video",
    displayName: "MiniMax Hailuo 2.3 Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.MINIMAX_HAILUO_2_3_I2V, {
        resolutionType: "1080P",
        duration: 6,
      }),
      ["1080P 6s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-hailuo-2.3-i2v",
    path: "/v3/async/minimax-hailuo-2.3-i2v",
    isNew: true,
    series: "MiniMax",
  },
  {
    id: "minimax-hailuo-2.3-fast-i2v",
    type: ModelType.Video,
    name: "MiniMax Hailuo 2.3 Fast Image to Video",
    displayName: "MiniMax Hailuo 2.3 Fast Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.MINIMAX_HAILUO_2_3_FAST_I2V, {
        resolutionType: "1080P",
        duration: 6,
      }),
      ["1080P 6s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-minimax-hailuo-2.3-fast-i2v",
    path: "/v3/async/minimax-hailuo-2.3-fast-i2v",
    isNew: true,
    series: "MiniMax",
  },
  {
    id: "kling-v1-6-t2v",
    type: ModelType.Video,
    name: "Kling V1.6 Text to Video",
    displayName: "Kling V1.6 Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.KLING_V1_6_T2V, {
        mode: "Standard",
        duration: 5,
        resolutionType: "720P",
      }),
      ["720P 5s"],
    ],
    link: "/models/image#kling-v1.6-t2v",
    path: "/v3/async/kling-v1.6-t2v",
    series: "Kling",
  },
  {
    id: "kling-v1-6-i2v",
    type: ModelType.Video,
    name: "Kling V1.6 Image to Video",
    displayName: "Kling V1.6 Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.KLING_V1_6_I2V, {
        mode: "Professional",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P Pro 5s"],
    ],
    link: "/models/image#kling-v1.6-i2v",
    path: "/v3/async/kling-v1.6-i2v",
    series: "Kling",
  },
  // Provided by dynamic config (trimmed-data: kling-v2.1-t2v-master, kling-v2.1-i2v, kling-v2.1-i2v-master)
  // {
  //   id: "KLING_V2_1_T2V_MASTER",
  //   type: ModelType.Video,
  //   name: "Kling V2.1 Master Text to Video",
  //   displayName: "Kling V2.1 Master Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V2_1_T2V_MASTER, {
  //       mode: "Master",
  //       duration: 5,
  //       resolutionType: "1080P",
  //     }),
  //     ["1080P Master 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.1-t2v-master",
  //   path: "/v3/async/kling-v2.1-t2v-master",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "KLING_V2_1_I2V",
  //   type: ModelType.Video,
  //   name: "Kling V2.1 Image to Video",
  //   displayName: "Kling V2.1 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V2_1_I2V, {
  //       mode: "Professional",
  //       duration: 5,
  //       resolutionType: "1080P",
  //     }),
  //     ["1080P Professional 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.1-i2v",
  //   path: "/v3/async/kling-v2.1-i2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "KLING_V2_1_I2V_MASTER",
  //   type: ModelType.Video,
  //   name: "Kling V2.1 Master Image to Video",
  //   displayName: "Kling V2.1 Master Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V2_1_I2V_MASTER, {
  //       mode: "Master",
  //       duration: 5,
  //       resolutionType: "1080P",
  //     }),
  //     ["1080P Master 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.1-i2v-master",
  //   path: "/v3/async/kling-v2.1-i2v-master",
  //   isNew: true,
  //   series: "Kling",
  // },
  {
    id: "KLING_V2_5_T2V",
    type: ModelType.Video,
    name: "Kling V2.5 Turbo Text to Video",
    displayName: "Kling V2.5 Turbo Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.KLING_V2_5_T2V, {
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-kling-2.5-turbo-t2v",
    path: "/v3/async/kling-2.5-turbo-t2v",
    isNew: true,
    series: "Kling",
  },
  {
    id: "KLING_V2_5_I2V",
    type: ModelType.Video,
    name: "Kling V2.5 Turbo Image to Video",
    displayName: "Kling V2.5 Turbo Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.KLING_V2_5_I2V, {
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-kling-2.5-turbo-i2v",
    path: "/v3/async/kling-2.5-turbo-i2v",
    isNew: true,
    series: "Kling",
  },
  // Provided by dynamic config (trimmed-data: kling-v2.6-pro-*)
  // {
  //   id: "KLING_V26_PRO_MOTION_CONTROL",
  //   type: ModelType.Video,
  //   name: "Kling V2.6 Pro Motion Control",
  //   displayName: "Kling V2.6 Pro Motion Control",
  //   tags: ["Motion Control"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.KLING_V26_PRO_MOTION_CONTROL,
  //       { resolutionType: "1080P" },
  //       "s",
  //     ),
  //     ["1080P"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.6-pro-motion-control",
  //   path: "/v3/async/kling-v2.6-pro-motion-control",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "KLING_V26_PRO_T2V",
  //   type: ModelType.Video,
  //   name: "Kling V2.6 Pro Text to Video",
  //   displayName: "Kling V2.6 Pro Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V26_PRO_T2V, {
  //       duration: 5,
  //       resolutionType: "1080P",
  //       audio: false,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.6-pro-t2v",
  //   path: "/v3/async/kling-v2.6-pro-t2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "KLING_V26_PRO_I2V",
  //   type: ModelType.Video,
  //   name: "Kling V2.6 Pro Image to Video",
  //   displayName: "Kling V2.6 Pro Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V26_PRO_I2V, {
  //       duration: 5,
  //       resolutionType: "1080P",
  //       audio: false,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v2.6-pro-i2v",
  //   path: "/v3/async/kling-v2.6-pro-i2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // Provided by dynamic config (trimmed-data: kling-v3.0-*)
  // {
  //   id: "kling-v3.0-std-t2v",
  //   type: ModelType.Video,
  //   name: "Kling v3.0 Standard Text-to-Video",
  //   displayName: "Kling v3.0 Standard Text-to-Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V30_STD_T2V, { audio: false }, "s"),
  //     ["Standard · No Audio"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v3.0-std-t2v",
  //   path: "/v3/async/kling-v3.0-std-t2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "kling-v3.0-std-i2v",
  //   type: ModelType.Video,
  //   name: "Kling v3.0 Standard Image-to-Video",
  //   displayName: "Kling v3.0 Standard Image-to-Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V30_STD_I2V, { audio: false }, "s"),
  //     ["Standard · No Audio"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v3.0-std-i2v",
  //   path: "/v3/async/kling-v3.0-std-i2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "kling-v3.0-pro-t2v",
  //   type: ModelType.Video,
  //   name: "Kling v3.0 Pro Text-to-Video",
  //   displayName: "Kling v3.0 Pro Text-to-Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V30_PRO_T2V, { audio: false }, "s"),
  //     ["Pro · No Audio"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v3.0-pro-t2v",
  //   path: "/v3/async/kling-v3.0-pro-t2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // {
  //   id: "kling-v3.0-pro-i2v",
  //   type: ModelType.Video,
  //   name: "Kling v3.0 Pro Image-to-Video",
  //   displayName: "Kling v3.0 Pro Image-to-Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.KLING_V30_PRO_I2V, { audio: false }, "s"),
  //     ["Pro · No Audio"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-v3.0-pro-i2v",
  //   path: "/v3/async/kling-v3.0-pro-i2v",
  //   isNew: true,
  //   series: "Kling",
  // },
  // Provided by dynamic config (trimmed-data: kling-o1-*)
  // {
  //   id: "kling-o1-reference-to-video",
  //   type: ModelType.Video,
  //   name: "Kling-o1 Reference to Video",
  //   displayName: "Kling-o1 Reference to Video",
  //   tags: ["Reference to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.KLING_O1_REFERENCE_TO_VIDEO_VIDEO_AND_IMG,
  //       { resolutionType: "720P" },
  //       "s",
  //     ),
  //     ["720P"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-o1-ref2v",
  //   path: "/v3/async/kling-o1-ref2v",
  //   series: "Kling",
  // },
  // {
  //   id: "kling-o1-img-to-video",
  //   type: ModelType.Video,
  //   name: "Kling-o1 Image to Video",
  //   displayName: "Kling-o1 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.KLING_O1_IMG_TO_VIDEO_720P_5S_TO_10S,
  //       { resolutionType: "720P", duration: 5 },
  //       "s",
  //     ),
  //     ["720P 5s-10s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-o1-i2v",
  //   path: "/v3/async/kling-o1-i2v",
  //   series: "Kling",
  // },
  // {
  //   id: "kling-o1-text-to-video",
  //   type: ModelType.Video,
  //   name: "Kling-o1 Text to Video",
  //   displayName: "Kling-o1 Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.KLING_O1_TEXT_TO_VIDEO_720P_5S_TO_10S,
  //       { resolutionType: "720P", duration: 5 },
  //       "s",
  //     ),
  //     ["720P 5s-10s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-o1-t2v",
  //   path: "/v3/async/kling-o1-t2v",
  //   series: "Kling",
  // },
  // {
  //   id: "kling-o1-edit-video",
  //   type: ModelType.Video,
  //   name: "Kling-o1 Edit Video",
  //   displayName: "Kling-o1 Edit Video",
  //   tags: ["Video Edit"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.KLING_O1_EDIT_VIDEO_FAST_720P_6S_TO_20S,
  //       { resolutionType: "720P", duration: 6 },
  //       "s",
  //     ),
  //     ["720P 6s-20s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-kling-o1-video-edit",
  //   path: "/v3/async/kling-o1-video-edit",
  //   series: "Kling",
  // },
  {
    id: "minimax-video-01",
    type: ModelType.Video,
    name: "MiniMax Video 01",
    displayName: "MiniMax Video 01",
    tags: ["Image to Video", "Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.MINIMAX_VIDEO_01, {
        resolutionType: "720P",
        duration: 6,
      }),
      ["720P 6s"],
    ],
    link: "/models/image#minimax-video-01",
    path: "/v3/async/minimax-video-01",
    series: "MiniMax",
  },
  // Provided by dynamic config (trimmed-data: wan-t2v, wan-i2v)
  // {
  //   id: "wan-2-1-t2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.1 Text to Video",
  //   displayName: "Wan 2.1 Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_T2V, {
  //       resolutionType: "1280*720",
  //       duration: 5,
  //     }),
  //     ["1280*720 5s"],
  //   ],
  //   link: "/models/image#wan-t2v",
  //   path: "/v3/async/wan-t2v",
  //   series: "Wan",
  // },
  // {
  //   id: "wan-2-1-i2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.1 Image to Video",
  //   displayName: "Wan 2.1 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_I2V, {
  //       resolutionType: "1280*720",
  //       duration: 5,
  //     }),
  //     ["1280*720 5s"],
  //   ],
  //   link: "/models/image#wan-i2v",
  //   path: "/v3/async/wan-i2v",
  //   series: "Wan",
  // },
  {
    id: "hunyuan-video-fast",
    type: ModelType.Video,
    name: "Hunyuan Video Fast",
    displayName: "Hunyuan Video Fast",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.HUNYUAN_VIDEO_FAST, {
        model: "hunyuan-video-fast",
        resolutionType: "1280*720",
        duration: 5,
      }),
      ["1280*720 5s"],
    ],
    link: "/models/image#hunyuan-video-fast",
    path: "/v3/async/hunyuan-video-fast",
    series: "Hunyuan",
  },
  // Provided by dynamic config (trimmed-data: wan-2.2-t2v, wan-2.2-i2v)
  // {
  //   id: "wan-2-2-t2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.2 Text to Video",
  //   displayName: "Wan 2.2 Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_2_T2V, {
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-wan2.2-t2v",
  //   path: "/v3/async/wan-2.2-t2v",
  //   isNew: true,
  //   series: "Wan",
  // },
  // {
  //   id: "wan-2-2-i2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.2 Image to Video",
  //   displayName: "Wan 2.2 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_2_I2V, {
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-wan2.2-i2v",
  //   path: "/v3/async/wan-2.2-i2v",
  //   isNew: true,
  //   series: "Wan",
  // },
  // Provided by dynamic config (trimmed-data: wan-2.5-t2v-preview, wan-2.5-i2v-preview)
  // {
  //   id: "wan-2-5-t2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.5 Text to Video",
  //   displayName: "Wan 2.5 Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_5_T2V, {
  //       model: "WAN25_PREVIEW_T2V_1080P_5S",
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-wan2.5-t2v",
  //   path: "/v3/async/wan-2.5-t2v-preview",
  //   isNew: true,
  //   series: "Wan",
  // },
  // {
  //   id: "wan-2-5-i2v",
  //   type: ModelType.Video,
  //   name: "Wan 2.5 Image to Video",
  //   displayName: "Wan 2.5 Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(FUNC_NAME.WAN_2_5_I2V, {
  //       model: "WAN25_PREVIEW_I2V_1080P_5S",
  //       resolutionType: "1080P",
  //       duration: 5,
  //     }),
  //     ["1080P 5s"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-wan2.5-i2v",
  //   path: "/v3/async/wan-2.5-i2v-preview",
  //   isNew: true,
  //   series: "Wan",
  // },
  {
    id: "vidu-q1-text2video",
    type: ModelType.Video,
    name: "Vidu Q1 Text to Video",
    displayName: "Vidu Q1 Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q1_TEXT2VIDEO, {
        mode: "general",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q1-txt2video",
    path: "/v3/async/vidu-q1-txt2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q1-img2video",
    type: ModelType.Video,
    name: "Vidu Q1 Image to Video",
    displayName: "Vidu Q1 Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q1_IMG2VIDEO, {
        mode: "general",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q1-img2video",
    path: "/v3/async/vidu-q1-img2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q1-startend2video",
    type: ModelType.Video,
    name: "Vidu Q1 Start End to Video",
    displayName: "Vidu Q1 Start End to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q1_STARTEND2VIDEO, {
        mode: "general",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q1-startend2video",
    path: "/v3/async/vidu-q1-startend2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q1-reference2video",
    type: ModelType.Video,
    name: "Vidu Q1 Reference to Video",
    displayName: "Vidu Q1 Reference to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q1_REFERENCE2VIDEO, {
        mode: "general",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q1-reference2video",
    path: "/v3/async/vidu-q1-reference2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-2-0-img2video",
    type: ModelType.Video,
    name: "Vidu 2.0 Image to Video",
    displayName: "Vidu 2.0 Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_2_0_IMG2VIDEO, {
        mode: "general",
        duration: 4,
        resolutionType: "1080P",
      }),
      ["1080P 4s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-2.0-img2video",
    path: "/v3/async/vidu-2.0-img2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-2-0-startend2video",
    type: ModelType.Video,
    name: "Vidu 2.0 Start End to Video",
    displayName: "Vidu 2.0 Start End to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_2_0_STARTEND2VIDEO, {
        mode: "general",
        duration: 4,
        resolutionType: "1080P",
      }),
      ["1080P 4s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-2.0-startend2video",
    path: "/v3/async/vidu-2.0-startend2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-2-0-reference2video",
    type: ModelType.Video,
    name: "Vidu 2.0 Reference to Video",
    displayName: "Vidu 2.0 Reference to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_2_0_REFERENCE2VIDEO, {
        mode: "general",
        duration: 4,
        resolutionType: "720P",
      }),
      ["720P 4s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-2.0-reference2video",
    path: "/v3/async/vidu-2.0-reference2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q2",
    type: ModelType.Video,
    name: "Vidu Q2",
    displayName: "Vidu Q2",
    tags: ["Text to Video", "Reference to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q2, {
        model: "VIDU_Q2_T2V_1080P",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "/docs/api-reference/model-apis-vidu-q2-text2video",
    path: "/v3/async/vidu-q2-text2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q2-pro",
    type: ModelType.Video,
    name: "Vidu Q2 Pro",
    displayName: "Vidu Q2 Pro",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q2_PRO, {
        model: "VIDU_Q2_PRO_I2V_1080P",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "/docs/api-reference/model-apis-vidu-q2-pro-startend2video",
    path: "/v3/async/vidu-q2-pro-startend2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q2-pro-fast",
    type: ModelType.Video,
    name: "Vidu Q2 Pro Fast",
    displayName: "Vidu Q2 Pro Fast",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q2_PRO_FAST, {
        model: "VIDU_Q2_PRO_FAST_I2V_1080P",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "/docs/api-reference/model-apis-vidu-q2-pro-fast-startend2video",
    path: "/v3/async/vidu-q2-pro-fast-startend2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q2-turbo",
    type: ModelType.Video,
    name: "Vidu Q2 Turbo",
    displayName: "Vidu Q2 Turbo",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q2_TURBO, {
        model: "VIDU_Q2_TURBO_I2V_1080P",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "/docs/api-reference/model-apis-vidu-q2-turbo-startend2video",
    path: "/v3/async/vidu-q2-turbo-startend2video",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q2-template",
    type: ModelType.Video,
    name: "Vidu Q2 Template",
    displayName: "Vidu Q2 Template",
    tags: ["Template to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDU_Q2_TEMPLATE, {
        model: "VIDU_Q2_TEMPLATE2VIDEO_CREDIT_8",
      }),
      ["Template"],
    ],
    link: "/docs/api-reference/model-apis-vidu-q2-template2video",
    path: "/v3/async/vidu-q2-template2video",
    isNew: true,
    series: "Vidu",
  },
  // Provided by dynamic config (trimmed-data: vidu-q3-pro-t2v, vidu-q3-pro-i2v)
  // {
  //   id: "vidu-q3-pro-t2v",
  //   type: ModelType.Video,
  //   name: "Vidu Q3 Pro Text to Video",
  //   displayName: "Vidu Q3 Pro Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.VIDU_Q3_PRO_T2V,
  //       {
  //         model: "VIDU_Q3_PRO_T2V_1080P_OFFPEAK",
  //         resolutionType: "1080P",
  //       },
  //       "s",
  //     ),
  //     ["1080P Off-Peak"],
  //   ],
  //   link: "/docs/api-reference/model-apis-vidu-q3-pro-t2v",
  //   path: "/v3/async/vidu-q3-pro-t2v",
  //   isNew: true,
  //   series: "Vidu",
  // },
  // {
  //   id: "vidu-q3-pro-i2v",
  //   type: ModelType.Video,
  //   name: "Vidu Q3 Pro Image to Video",
  //   displayName: "Vidu Q3 Pro Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.VIDU_Q3_PRO_I2V,
  //       {
  //         model: "VIDU_Q3_PRO_I2V_1080P_OFFPEAK",
  //         resolutionType: "1080P",
  //       },
  //       "s",
  //     ),
  //     ["1080P Off-Peak"],
  //   ],
  //   link: "/docs/api-reference/model-apis-vidu-q3-pro-i2v",
  //   path: "/v3/async/vidu-q3-pro-i2v",
  //   isNew: true,
  //   series: "Vidu",
  // },
  {
    id: "vidu-q3-pro-f2v",
    type: ModelType.Video,
    name: "Vidu Q3 Pro Start-End-to-Video",
    displayName: "Vidu Q3 Pro Start-End-to-Video",
    tags: ["Start-End Frame to Video"],
    infos: [
      getVideoModelPrice(
        FUNC_NAME.VIDU_Q3_PRO_F2V,
        {
          model: "VIDU_Q3_PRO_F2V_1080P_OFFPEAK",
          resolutionType: "1080P",
        },
        "s",
      ),
      ["1080P Off-Peak"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q3-pro-f2v",
    path: "/v3/async/vidu-q3-pro-f2v",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q3-turbo-t2v",
    type: ModelType.Video,
    name: "Vidu Q3 Turbo Text-to-Video",
    displayName: "Vidu Q3 Turbo Text-to-Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(
        FUNC_NAME.VIDU_Q3_TURBO_T2V,
        {
          model: "VIDU_Q3_TURBO_T2V_1080P_OFFPEAK",
          resolutionType: "1080P",
        },
        "s",
      ),
      ["1080P Off-Peak"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q3-turbo-t2v",
    path: "/v3/async/vidu-q3-turbo-t2v",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q3-turbo-i2v",
    type: ModelType.Video,
    name: "Vidu Q3 Turbo Image-to-Video",
    displayName: "Vidu Q3 Turbo Image-to-Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(
        FUNC_NAME.VIDU_Q3_TURBO_I2V,
        {
          model: "VIDU_Q3_TURBO_I2V_1080P_OFFPEAK",
          resolutionType: "1080P",
        },
        "s",
      ),
      ["1080P Off-Peak"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q3-turbo-i2v",
    path: "/v3/async/vidu-q3-turbo-i2v",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "vidu-q3-turbo-f2v",
    type: ModelType.Video,
    name: "Vidu Q3 Turbo Start-End-to-Video",
    displayName: "Vidu Q3 Turbo Start-End-to-Video",
    tags: ["Start-End Frame to Video"],
    infos: [
      getVideoModelPrice(
        FUNC_NAME.VIDU_Q3_TURBO_F2V,
        {
          model: "VIDU_Q3_TURBO_F2V_1080P_OFFPEAK",
          resolutionType: "1080P",
        },
        "s",
      ),
      ["1080P Off-Peak"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-vidu-q3-turbo-f2v",
    path: "/v3/async/vidu-q3-turbo-f2v",
    isNew: true,
    series: "Vidu",
  },
  {
    id: "pixverse-v4-5-t2v",
    type: ModelType.Video,
    name: "PixVerse V4.5 Text to Video",
    displayName: "PixVerse V4.5 Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.PIXVERSE_V4_5_T2V, {
        mode: "fast_mode",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-pixverse-v4.5-t2v",
    path: "/v3/async/pixverse-v4.5-t2v",
    series: "PixVerse",
  },
  {
    id: "pixverse-v4-5-i2v",
    type: ModelType.Video,
    name: "PixVerse V4.5 Image to Video",
    displayName: "PixVerse V4.5 Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.PIXVERSE_V4_5_I2V, {
        mode: "fast_mode",
        duration: 5,
        resolutionType: "1080P",
      }),
      ["1080P 5s"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-pixverse-v4.5-i2v",
    path: "/v3/async/pixverse-v4.5-i2v",
    series: "PixVerse",
  },
  {
    id: "SEEDANCE_V1_LITE_T2V",
    type: ModelType.Video,
    name: "Seedance V1.0 Lite Text to Video",
    displayName: "Seedance V1.0 Lite Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.SEEDANCE_V1_LITE_T2V, {
        mode: "Standard",
        duration: 5,
        resolutionType: "1080P",
        ratio: "16:9",
      }),
      ["1080P 5s 16:9"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1-lite-t2v",
    path: "/v3/async/seedance-v1-lite-t2v",
    isNew: true,
    series: "Seedance",
  },
  {
    id: "SEEDANCE_V1_LITE_I2V",
    type: ModelType.Video,
    name: "Seedance V1.0 Lite Image to Video",
    displayName: "Seedance V1.0 Lite Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.SEEDANCE_V1_LITE_I2V, {
        mode: "Standard",
        duration: 5,
        resolutionType: "1080P",
        ratio: "16:9",
      }),
      ["1080P 5s 16:9"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1-lite-i2v",
    path: "/v3/async/seedance-v1-lite-i2v",
    isNew: true,
    series: "Seedance",
  },
  {
    id: "SEEDANCE_V1_PRO_T2V",
    type: ModelType.Video,
    name: "Seedance V1.0 Pro Text to Video",
    displayName: "Seedance V1.0 Pro Text to Video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.SEEDANCE_V1_PRO_T2V, {
        mode: "Standard",
        duration: 5,
        resolutionType: "1080P",
        ratio: "16:9",
      }),
      ["1080P 5s 16:9"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1-pro-t2v",
    path: "/v3/async/seedance-v1-pro-t2v",
    isNew: true,
    series: "Seedance",
  },
  {
    id: "SEEDANCE_V1_PRO_I2V",
    type: ModelType.Video,
    name: "Seedance V1.0 Pro Image to Video",
    displayName: "Seedance V1.0 Pro Image to Video",
    tags: ["Image to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.SEEDANCE_V1_PRO_I2V, {
        mode: "Standard",
        duration: 5,
        resolutionType: "1080P",
        ratio: "16:9",
      }),
      ["1080P 5s 16:9"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1-pro-i2v",
    path: "/v3/async/seedance-v1-pro-i2v",
    isNew: true,
    series: "Seedance",
  },
  // Provided by dynamic config (trimmed-data: seedance-1.5-pro-t2v, seedance-1.5-pro-i2v)
  // {
  //   id: "SEEDANCE_V15_PRO_T2V",
  //   type: ModelType.Video,
  //   name: "Seedance 1.5 Pro Text to Video",
  //   displayName: "Seedance 1.5 Pro Text to Video",
  //   tags: ["Text to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.SEEDANCE_V15_PRO_T2V,
  //       {
  //         resolutionType: "720P",
  //         audioType: "SILENT",
  //         batchMode: "ONLINE",
  //       },
  //       "s",
  //     ),
  //     ["720P SILENT ONLINE"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1.5-pro-t2v",
  //   path: "/v3/async/seedance-v1.5-pro-t2v",
  //   isNew: true,
  //   series: "Seedance",
  // },
  // {
  //   id: "SEEDANCE_V15_PRO_I2V",
  //   type: ModelType.Video,
  //   name: "Seedance 1.5 Pro Image to Video",
  //   displayName: "Seedance 1.5 Pro Image to Video",
  //   tags: ["Image to Video"],
  //   infos: [
  //     getVideoModelPrice(
  //       FUNC_NAME.SEEDANCE_V15_PRO_I2V,
  //       {
  //         resolutionType: "720P",
  //         frameType: "FLF",
  //         audioType: "SILENT",
  //         batchMode: "ONLINE",
  //       },
  //       "s",
  //     ),
  //     ["720P FLF SILENT ONLINE"],
  //   ],
  //   link: "https://novita.ai/docs/api-reference/model-apis-seedance-v1.5-pro-i2v",
  //   path: "/v3/async/seedance-v1.5-pro-i2v",
  //   isNew: true,
  //   series: "Seedance",
  // },
  {
    id: "txt2video",
    type: ModelType.Video,
    name: FUNC_NAME.TXT2VIDEO,
    displayName: "Text to video",
    tags: ["Text to Video"],
    infos: [
      getVideoModelPrice(FUNC_NAME.TXT2VIDEO, { frames: 32, steps: 20 }),
      ["32 frames 20 steps"],
    ],
    link: "/models/image#txt2video",
    path: "",
    series: "Others",
  },
  {
    id: "video-merge-face",
    type: ModelType.Video,
    name: FUNC_NAME.VIDEO_MERGE_FACE,
    displayName: "Video Merge Face",
    tags: ["Video Edit"],
    infos: [
      getVideoModelPrice(FUNC_NAME.VIDEO_MERGE_FACE, {
        model: "SVD",
        steps: 5,
      }),
      ["SVD 5 steps"],
    ],
    link: "https://novita.ai/docs/api-reference/model-apis-video-merge-face",
    path: "/v3/async/video-merge-face",
    series: "Others",
  },
  // Provided by dynamic config (trimmed-data: heygen-video-translate)
  // {
  //   id: "heygen-video-translate",
  //   type: ModelType.Video,
  //   name: "Heygen Video-translate",
  //   displayName: "Heygen Video-translate",
  //   tags: ["Video Translate"],
  //   infos: [getVideoModelPrice(FUNC_NAME.HEYGEN_VIDEO_TRANSLATE, {}, "s")],
  //   link: "https://novita.ai/docs/api-reference/model-apis-heygen-video-translate",
  //   path: "/v3/async/heygen-video-translate",
  //   isNew: true,
  //   series: "Heygen",
  // },
];
