export const mockConsumeMonthlyData: consumeMonthlySchema = [
  {
    month: "Jan",
    gpu_instance: "100",
    model_api: "150",
    serverless: "80",
    storage: "50",
    cloud_sandbox: "30",
    llm_dedicated_endpoint: "20",
  },
  {
    month: "Feb",
    gpu_instance: "120",
    model_api: "180",
    serverless: "90",
    storage: "60",
    cloud_sandbox: "35",
    llm_dedicated_endpoint: "25",
  },
  {
    month: "Mar",
    gpu_instance: "110",
    model_api: "160",
    serverless: "85",
    storage: "55",
    cloud_sandbox: "32",
    llm_dedicated_endpoint: "22",
  },
  {
    month: "Apr",
    gpu_instance: "130",
    model_api: "200",
    serverless: "95",
    storage: "65",
    cloud_sandbox: "40",
    llm_dedicated_endpoint: "30",
  },
  {
    month: "May",
    gpu_instance: "140",
    model_api: "220",
    serverless: "100",
    storage: "70",
    cloud_sandbox: "45",
    llm_dedicated_endpoint: "35",
  },
  {
    month: "Jun",
    gpu_instance: "150",
    model_api: "240",
    serverless: "110",
    storage: "75",
    cloud_sandbox: "50",
    llm_dedicated_endpoint: "40",
  },
];
