import { DOCS_URL } from "@/constants/urls";
const modelApiConstantFUNCDISPLAYNAME = {
  TXT2IMG: "Text to Image",
  txt2img: "Text to Image",
  IMG2IMG: "Image to Image",
  img2img: "Image to Image",
  LCM_TXT2IMG: "LCM Text to Image",
  "lcm-txt2img": "LCM Text to Image",
  REMOVE_BACKGROUND: "Remove Background",
  "remove-background": "Remove Background",
  REPLACE_BACKGROUND: "Replace Background",
  "replace-background": "Replace Background",
  CLEANUP: "Cleanup",
  cleanup: "Cleanup",
  OUTPAINTING: "Outpainting",
  outpainting: "Outpainting",
  MIX_POSE: "Mix Pose",
  "mix-pose": "Mix Pose",
  DOODLE: "Doodle",
  doodle: "Doodle",
  UPSCALE: "Upscale",
  upscale: "Upscale",
  MERGE_FACE: "Merge Face",
  "merge-face": "Merge Face",
  REPLACE_SKY: "Replace Sky",
  "replace-sky": "Replace Sky",
  REPLACE_OBJECT: "Replace Object",
  "replace-object": "Replace Object",
  REMOVE_TEXT: "Remove Text",
  "remove-text": "Remove Text",
  RESTORE_FACE: "Restore Face",
  "restore-face": "Restore Face",
  MAKE_PHOTO: "Make Photo",
  "make-photo": "Make Photo",
  TILE: "Create Tile",
  "create-tile": "Create Tile",
  REIMAGINE: "Reimagine",
  reimagine: "Reimagine",
  INPAINTING: "Inpainting",
  inpainting: "Inpainting",
  SDXL: "SDXL",
  LORA: "LoRA",
  LoRA: "LoRA",
  REFINER: "Refiner",
  refiner: "Refiner",
  HUNYUAN_VIDEO_FAST: "Hunyuan Video Fast",
  "hunyuan-video-fast": "Hunyuan Video Fast",
  WAN_T2V: "Wan 2.1 Text to Video",
  "wan-t2v": "Wan 2.1 Text to Video",
  WAN_I2V: "Wan 2.1 Image to Video",
  "wan-i2v": "Wan 2.1 Image to Video",
  "WAN_2.2_T2V": "Wan 2.2 Text to Video",
  "wan-2.2-t2v": "Wan 2.2 Text to Video",
  "WAN_2.2_I2V": "Wan 2.2 Image to Video",
  "wan-2.2-i2v": "Wan 2.2 Image to Video",
  QWEN_TXT2IMG: "Qwen-Image Text to Image",
  "qwen-txt2img": "Qwen-Image Text to Image",
  QWEN_IMAGE_EDIT: "Qwen-Image Edit",
  "qwen-image-edit": "Qwen-Image Edit",
  SEEDREAM_3_0_T2I: "Seedream 3.0 Text to Image",
  "seedream-3.0-t2i": "Seedream 3.0 Text to Image",
  SEEDREAM_4_0: "Seedream 4.0",
  "seedream-4.0": "Seedream 4.0",
  SEEDREAM_4_5: "Seedream 4.5",
  "seedream-4.5": "Seedream 4.5",
  SEEDANCE_V1_LITE_T2V: "Seedance V1 Lite Text to Video",
  "seedance-v1-lite-t2v": "Seedance V1 Lite Text to Video",
  SEEDANCE_V1_LITE_I2V: "Seedance V1 Lite Image to Video",
  "seedance-v1-lite-i2v": "Seedance V1 Lite Image to Video",
  SEEDANCE_V1_PRO_T2V: "Seedance V1 Pro Text to Video",
  "seedance-v1-pro-t2v": "Seedance V1 Pro Text to Video",
  SEEDANCE_V1_PRO_I2V: "Seedance V1 Pro Image to Video",
  "seedance-v1-pro-i2v": "Seedance V1 Pro Image to Video",
  "KLING_V1.6_T2V": "Kling V1.6 Text to Video",
  "kling-v1.6-t2v": "Kling V1.6 Text to Video",
  "KLING_V1.6_I2V": "Kling V1.6 Image to Video",
  "kling-v1.6-i2v": "Kling V1.6 Image to Video",
  "KLING_V2.1_T2V_MASTER": "Kling V2.1 Master Text to Video",
  "kling-v2.1-t2v-master": "Kling V2.1 Master Text to Video",
  "KLING_V2.1_T2V": "Kling V2.1 Text to Video",
  "kling-v2.1-i2v": "Kling V2.1 Image to Video",
  "KLING_V2.1_I2V_MASTER": "Kling V2.1 Master Image to Video",
  "kling-v2.1-i2v-master": "Kling V2.1 Master Image to Video",
  MINIMAX_VIDEO_01: "Minimax Video 01",
  "minimax-video-01": "Minimax Video 01",
  MINIMAX_HAILUO_02: "Minimax Hailuo 02",
  "minimax-hailuo-02": "Minimax Hailuo 02",
  VIDU_Q1_TEXT2VIDEO: "Vidu Q1 Text to Video",
  "vidu-q1-text2video": "Vidu Q1 Text to Video",
  VIDU_Q1_IMG2VIDEO: "Vidu Q1 Image to Video",
  "vidu-q1-img2video": "Vidu Q1 Image to Video",
  VIDU_Q1_STARTEND2VIDEO: "Vidu Q1 Start End to Video",
  "vidu-q1-startend2video": "Vidu Q1 Start End to Video",
  VIDU_Q1_REFERENCE2VIDEO: "Vidu Q1 Reference to Video",
  "vidu-q1-reference2video": "Vidu Q1 Reference to Video",
  "VIDU_2.0_IMG2VIDEO": "Vidu 2.0 Image to Video",
  "vidu-2.0-img2video": "Vidu 2.0 Image to Video",
  "VIDU_2.0_STARTEND2VIDEO": "Vidu 2.0 Start End to Video",
  "vidu-2.0-startend2video": "Vidu 2.0 Start End to Video",
  "VIDU_2.0_REFERENCE2VIDEO": "Vidu 2.0 Reference to Video",
  "vidu-2.0-reference2video": "Vidu 2.0 Reference to Video",
  "PIXVERSE_V4.5_I2V": "Pixverse V4.5 Image to Video",
  "pixverse-v4.5-i2v": "Pixverse V4.5 Image to Video",
  "PIXVERSE_V4.5_T2V": "Pixverse V4.5 Text to Video",
  "pixverse-v4.5-t2v": "Pixverse V4.5 Text to Video",
  TXT2VIDEO: "Text to Video",
  txt2video: "Text to Video",
  IMG2VIDEO: "Image to Video",
  img2video: "Image to Video",
  SDXL_TURBO: "SDXL-Turbo",
  "sdxl-turbo": "SDXL-Turbo",
  REMOVE_WATERMARK: "Remove Watermark",
  "remove-watermark": "Remove Watermark",
  LCM_IMG2IMG: "LCM Image to Image",
  "lcm-img2img": "LCM Image to Image",
  TRAINING: "LoRA Training",
  "LoRA-training": "LoRA Training",
  MOTIONSYNC: "Image to Video - Motion",
  "img2video-motion": "Image to Video - Motion",
  ANIMATE_ANYONE: "Animate Anyone",
  "animate-anyone": "Animate Anyone",
  VIDEO_MAGIC_CUT: "Video Magic Cut",
  "video-magic-cut": "Video Magic Cut",
  VIDEO_MERGE_FACE: "Video Merge Face",
  "video-merge-face": "Video Merge Face",
  VIDEO_REMOVE_OBJECT: "Video Remove Object",
  "video-remove-object": "Video Remove Object",
  VIDEO_REMOVE_WATERMARK: "Video Remove Watermark",
  "video-remove-watermark": "Video Remove Watermark",
  VIDEO_REMOVE_SUBTITLE: "Video Remove Subtitle",
  "video-remove-subtitle": "Video Remove Subtitle",
  VIDEO_TRANSLATE: "Video Translate",
  "video-translate": "Video Translate",
  VIDEO_UPSCALE: "Video Upscale",
  "video-upscale": "Video Upscale",
  SPEECH2TXT: "Speech to Text",
  speech2txt: "Speech to Text",
  SPEECH2TXT_TRANSLATE: "Speech to Text - Translate",
  "speech2txt-translate": "Speech to Text - Translate",
  TXT2SPEECH: "Text to Speech",
  txt2speech: "Text to Speech",
  VOICE_CLONING_INSTANT: "Voice Cloning - Instant",
  "voice-cloning-instant": "Voice Cloning - Instant",
  VOICE_CLONING: "Voice Cloning",
  "voice-cloning": "Voice Cloning",
  MINIMAX_SPEECH_02_HD: "Minimax speech-02-hd",
  "minimax-speech-02-hd": "Minimax speech-02-hd",
  MINIMAX_SPEECH_02_TURBO: "Minimax speech-02-turbo",
  "minimax-speech-02-turbo": "Minimax speech-02-turbo",
  "MINIMAX_SPEECH_2.5_HD_PREVIEW": "Minimax speech-2.5-hd-preview",
  "minimax-speech-2.5-hd-preview": "Minimax speech-2.5-hd-preview",
  "MINIMAX_SPEECH_2.5_TURBO_PREVIEW": "Minimax speech-2.5-turbo-preview",
  "minimax-speech-2.5-turbo-preview": "Minimax speech-2.5-turbo-preview",
  MINIMAX_SPEECH_2_6_HD: "Minimax speech-2.6-hd",
  "minimax-speech-2.6-hd": "Minimax speech-2.6-hd",
  MINIMAX_SPEECH_2_6_TURBO: "Minimax speech-2.6-turbo",
  "minimax-speech-2.6-turbo": "Minimax speech-2.6-turbo",
  MINIMAX_VOICE_CLONING: "Minimax Voice-Cloning",
  "minimax-voice-cloning": "Minimax Voice-Cloning",
  LLM_CHAT: "LLM API",
  "llm-chat": "LLM API",
  RELIGHT: "Relight",
  relight: "Relight",
  ADETAILER: "ADetailer",
  adetailer: "ADetailer",
  IMG2MASK: "Image to Mask",
  img2mask: "Image to Mask",
  IMG2PROMPT: "Image to Prompt",
  img2prompt: "Image to Prompt",
  Facefusion: "Facefusion",
  FLUX1: "FLUX.1",
  FLUX1_KONTEXT_DEV: "FLUX.1 Kontext Dev",
  "flux1-kontext-dev": "FLUX.1 Kontext Dev",
  FLUX1_KONTEXT_PRO: "FLUX.1 Kontext Pro",
  "flux1-kontext-pro": "FLUX.1 Kontext Pro",
  FLUX1_KONTEXT_MAX: "FLUX.1 Kontext Max",
  "flux1-kontext-max": "FLUX.1 Kontext Max",
};
const modelApiConstantMainpage = {
  LLM_CHAT: "",
  TXT2IMG: "",
  IMG2IMG: "",
  MERGE_FACE: "",
  TXT2VIDEO: "",
  TXT2VOICE: "",
};
export type FuncConstants = {
  name: string;
  type: symbol;
  displayName: string;
  docUrl?: string;
  getStartedUrl?: string;
  playgroundReady: boolean;
  productpageReady: boolean;
  cover?: string;
  coverAlt?: string;
  showcaseVideo?: {
    src: string;
    type: string;
  }[];
  url?: string;
};
export type FuncData = {
  type: symbol;
  smallIcon: string;
  url?: string;
} & FuncConstants;
export const SAMPLER_OPTIONS = [
  "Euler a",
  "Euler",
  "LMS",
  "Heun",
  "DPM2",
  "DPM2 a",
  "DPM++ 2S a",
  "DPM++ 2M",
  "DPM++ SDE",
  "DPM fast",
  "DPM adaptive",
  "LMS Karras",
  "DPM2 Karras",
  "DPM2 a Karras",
  "DPM++ 2S a Karras",
  "DPM++ 2M Karras",
  "DPM++ SDE Karras",
  "DDIM",
  "PLMS",
  "UniPC",
];
export enum FUNC_NAME {
  TXT2IMG = "txt2img",
  IMG2IMG = "img2img",
  SD3_TXT2IMG = "sd3-txt2img",
  SD3_IMG2IMG = "sd3-img2img",
  LCM_TXT2IMG = "lcm-txt2img",
  REMOVE_BACKGROUND = "remove-background",
  REPLACE_BACKGROUND = "replace-background",
  CLEANUP = "cleanup",
  OUTPAINTING = "outpainting",
  MIX_POSE = "mix-pose",
  DOODLE = "doodle",
  UPSCALE = "upscale",
  IMAGE_REMOVE_BACKGROUND = "image-remove-background",
  IMAGE_ERASER = "image-eraser",
  IMAGE_UPSCALER = "image-upscaler",
  MERGE_FACE = "merge-face",
  REPLACE_SKY = "replace-sky",
  REPLACE_OBJECT = "replace-object",
  REMOVE_TEXT = "remove-text",
  RESTORE_FACE = "restore-face",
  TILE = "create-tile",
  REIMAGINE = "reimagine",
  INPAINTING = "inpainting",
  SDXL = "SDXL",
  LORA = "LoRA",
  REFINER = "refiner",
  WAN_T2V = "wan-t2v",
  WAN_I2V = "wan-i2v",
  WAN_2_2_T2V = "wan-2.2-t2v",
  WAN_2_2_I2V = "wan-2.2-i2v",
  WAN_2_5_T2V = "wan-2.5-t2v",
  WAN_2_5_I2V = "wan-2.5-i2v",
  WAN_2_6_T2V = "wan-2.6-t2v",
  WAN_2_6_I2V = "wan-2.6-i2v",
  WAN_2_6_V2V = "wan-2.6-v2v",
  VIDU_Q1_TEXT2VIDEO = "vidu-q1-text2video",
  VIDU_Q1_IMG2VIDEO = "vidu-q1-img2video",
  VIDU_Q1_STARTEND2VIDEO = "vidu-q1-startend2video",
  VIDU_Q1_REFERENCE2VIDEO = "vidu-q1-reference2video",
  VIDU_2_0_IMG2VIDEO = "vidu-2.0-img2video",
  VIDU_2_0_STARTEND2VIDEO = "vidu-2.0-startend2video",
  VIDU_2_0_REFERENCE2VIDEO = "vidu-2.0-reference2video",
  VIDU_Q2 = "vidu-q2",
  VIDU_Q2_PRO = "vidu-q2-pro",
  VIDU_Q2_PRO_FAST = "vidu-q2-pro-fast",
  VIDU_Q2_TURBO = "vidu-q2-turbo",
  VIDU_Q2_TEMPLATE = "vidu-q2-template",
  VIDU_Q3_PRO_T2V = "vidu-q3-pro-t2v",
  VIDU_Q3_PRO_I2V = "vidu-q3-pro-i2v",
  VIDU_Q3_PRO_F2V = "vidu-q3-pro-f2v",
  VIDU_Q3_TURBO_T2V = "vidu-q3-turbo-t2v",
  VIDU_Q3_TURBO_I2V = "vidu-q3-turbo-i2v",
  VIDU_Q3_TURBO_F2V = "vidu-q3-turbo-f2v",
  PIXVERSE_V4_5_I2V = "pixverse-v4.5-i2v",
  PIXVERSE_V4_5_T2V = "pixverse-v4.5-t2v",
  QWEN_TXT2IMG = "qwen-txt2img",
  QWEN_IMAGE_EDIT = "qwen-image-edit",
  GLM_IMAGE = "glm-image",
  SEEDREAM_3_0_T2I = "seedream-3.0-t2i",
  SEEDREAM_4_0 = "seedream-4.0",
  SEEDREAM_4_5 = "seedream-4.5",
  SEEDANCE_V1_LITE_T2V = "seedance-v1-lite-t2v",
  SEEDANCE_V1_LITE_I2V = "seedance-v1-lite-i2v",
  SEEDANCE_V1_PRO_T2V = "seedance-v1-pro-t2v",
  SEEDANCE_V1_PRO_I2V = "seedance-v1-pro-i2v",
  SEEDANCE_V15_PRO_T2V = "seedance-v1.5-pro-t2v",
  SEEDANCE_V15_PRO_I2V = "seedance-v1.5-pro-i2v",
  HUNYUAN_VIDEO_FAST = "hunyuan-video-fast",
  HUNYUAN_3_0 = "hunyuan-3.0",
  KLING_V1_6_T2V = "kling-v1.6-t2v",
  KLING_V1_6_I2V = "kling-v1.6-i2v",
  KLING_V2_1_T2V_MASTER = "kling-v2.1-t2v-master",
  KLING_V2_1_I2V = "kling-v2.1-i2v",
  KLING_V2_1_I2V_MASTER = "kling-v2.1-i2v-master",
  KLING_V2_5_T2V = "kling-v2.5-t2v",
  KLING_V2_5_I2V = "kling-v2.5-i2v",
  KLING_V26_PRO_MOTION_CONTROL = "kling-v2.6-pro-motion-control",
  KLING_V26_PRO_T2V = "kling-v2.6-pro-t2v",
  KLING_V26_PRO_I2V = "kling-v2.6-pro-i2v",
  KLING_V30_STD_T2V = "kling-v3.0-std-t2v",
  KLING_V30_STD_I2V = "kling-v3.0-std-i2v",
  KLING_V30_PRO_T2V = "kling-v3.0-pro-t2v",
  KLING_V30_PRO_I2V = "kling-v3.0-pro-i2v",
  KLING_O1_REFERENCE_TO_VIDEO_VIDEO_AND_IMG = "kling-o1-reference-to-video-video-and-img",
  KLING_O1_REFERENCE_TO_VIDEO_ONLY_VIDEO = "kling-o1-reference-to-video-only-video",
  KLING_O1_REFERENCE_TO_VIDEO_ONLY_IMG = "kling-o1-reference-to-video-only-img",
  KLING_O1_IMG_TO_VIDEO_720P_5S_TO_10S = "kling-o1-img-to-video-720p-5s-to-10s",
  KLING_O1_TEXT_TO_VIDEO_720P_5S_TO_10S = "kling-o1-text-to-video-720p-5s-to-10s",
  KLING_O1_EDIT_VIDEO_FAST_720P_6S_TO_20S = "kling-o1-edit-video-fast-720p-6s-to-20s",
  KLING_O1_EDIT_VIDEO_720P_3S_TO_10S_VIDEO = "kling-o1-edit-video-720p-3s-to-10s-video",
  MINIMAX_VIDEO_01 = "minimax-video-01",
  MINIMAX_HAILUO_02 = "minimax-hailuo-02",
  MINIMAX_HAILUO_2_3_T2V = "minimax-hailuo-2.3-t2v",
  MINIMAX_HAILUO_2_3_I2V = "minimax-hailuo-2.3-i2v",
  MINIMAX_HAILUO_2_3_FAST_I2V = "minimax-hailuo-2.3-fast-i2v",
  TXT2VIDEO = "txt2video",
  IMG2VIDEO = "img2video",
  SDXL_TURBO = "sdxl-turbo",
  REMOVE_WATERMARK = "remove-watermark",
  LCM_IMG2IMG = "lcm-img2img",
  TRAINING = "LoRA-training",
  MOTIONSYNC = "img2video-motion",
  ANIMATE_ANYONE = "animate-anyone",
  VIDEO_MAGIC_CUT = "video-magic-cut",
  VIDEO_MERGE_FACE = "video-merge-face",
  VIDEO_REMOVE_OBJECT = "video-remove-object",
  VIDEO_REMOVE_WATERMARK = "video-remove-watermark",
  VIDEO_REMOVE_SUBTITLE = "video-remove-subtitle",
  VIDEO_TRANSLATE = "video-translate",
  HEYGEN_VIDEO_TRANSLATE = "heygen-video-translate",
  VIDEO_UPSCALE = "video-upscale",
  SPEECH2TXT = "speech2txt",
  SPEECH2TXT_TRANSLATE = "speech2txt-translate",
  TXT2SPEECH = "txt2speech",
  MINIMAX_SPEECH_02_HD = "minimax-speech-02-hd",
  MINIMAX_SPEECH_02_TURBO = "minimax-speech-02-turbo",
  MINIMAX_VOICE_CLONING = "minimax-voice-cloning",
  MINIMAX_SPEECH_2_5_HD_PREVIEW = "minimax-speech-2.5-hd-preview",
  MINIMAX_SPEECH_2_5_TURBO_PREVIEW = "minimax-speech-2.5-turbo-preview",
  MINIMAX_SPEECH_2_6_TURBO = "minimax-speech-2.6-turbo",
  MINIMAX_SPEECH_2_6_HD = "minimax-speech-2.6-hd",
  MINIMAX_SPEECH_2_8_TURBO = "minimax-speech-2.8-turbo",
  MINIMAX_SPEECH_2_8_HD = "minimax-speech-2.8-hd",
  FISH_AUDIO_TEXT_TO_SPEECH = "fish-audio-text-to-speech",
  FISH_AUDIO_VOICE_CLONING = "fish-audio-voice-cloning",
  ELEVEN_CORE_V3_TTS = "eleven-core-v3-tts",
  ELEVEN_SCRIBE_V2_ASR = "eleven-scribe-v2-asr",
  ELEVEN_CLONE_V1_VOICE = "eleven-clone-v1-voice",
  GLM_TTS = "glm-tts",
  GLM_TTS_CLONE = "glm-tts-clone",
  GLM_ASR_2512 = "glm-asr-2512",
  VOICE_CLONING_INSTANT = "voice-cloning-instant",
  VOICE_CLONING = "voice-cloning",
  LLM_CHAT = "llm-chat",
  MAKE_PHOTO = "make-photo",
  RELIGHT = "relight",
  ADETAILER = "adetailer",
  IMG2MASK = "img2mask",
  IMG2PROMPT = "img2prompt",
  FACEFUSION = "facefusion",
  FLUX1 = "FLUX.1",
  FLUX1_KONTEXT_DEV = "flux1-kontext-dev",
  FLUX1_KONTEXT_PRO = "flux1-kontext-pro",
  FLUX1_KONTEXT_MAX = "flux1-kontext-max",
  FLUX_2_DEV_TXT_TO_IMG = "flux-2-dev-txt-to-img",
  FLUX_2_DEV_IMG_TO_IMG = "flux-2-dev-img-to-img",
  FLUX_2_DEV_LORA_TXT_TO_IMG = "flux-2-dev-lora-txt-to-img",
  FLUX_2_DEV_LORA_IMG_TO_IMG = "flux-2-dev-lora-img-to-img",
  FLUX_2_FLEX_TXT_TO_IMG = "flux-2-flex-txt-to-img",
  FLUX_2_FLEX_IMG_TO_IMG = "flux-2-flex-img-to-img",
  FLUX_2_PRO_TXT_TO_IMG = "flux-2-pro-txt-to-img",
  FLUX_2_PRO_IMG_TO_IMG = "flux-2-pro-img-to-img",
  Z_IMAGE_TURBO_LORA = "z-image-turbo-lora",
  Z_IMAGE_TURBO = "z-image-turbo",
}
export const FUNC_DISPLAY_NAME = modelApiConstantFUNCDISPLAYNAME;
export const Main_Page_FUNCNAME = modelApiConstantMainpage;
export const FUNC_DISABLE_IN_EN: string[] = [FUNC_NAME.FACEFUSION];
export const FUNC_TYPE = {
  IMG: Symbol("img"),
  IMG_GENERATOR: Symbol("img_generator"),
  IMG_EDITOR: Symbol("img_editor"),
  FACE_EDITOR: Symbol("face_editor"),
  TRAINING: Symbol("training"),
  VIDEO_GENERATOR: Symbol("video_generator"),
  AUDIO: Symbol("audio"),
  LLM: Symbol("llm"),
  EMBEDDING: Symbol("embedding"),
};
export const FUNC_TYPE_NAME = {
  [FUNC_TYPE.IMG]: "Image",
  [FUNC_TYPE.IMG_GENERATOR]: "Image Generator",
  [FUNC_TYPE.IMG_EDITOR]: "Image Editor",
  [FUNC_TYPE.FACE_EDITOR]: "Face Editor",
  [FUNC_TYPE.TRAINING]: "Training",
  [FUNC_TYPE.VIDEO_GENERATOR]: "Video",
  [FUNC_TYPE.AUDIO]: "Audio",
  [FUNC_TYPE.LLM]: "LLMs",
  [FUNC_TYPE.EMBEDDING]: "Embeddings",
};
export type ProductType = {
  icon: string;
  image: string;
  text: string;
  link: string;
};
export const Tools_Map: Record<string, Array<ProductType>> = {
  "AI Image Generator": [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "txt2img",
      link: "/product/txt2img",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "img2img",
      link: "/product/img2img",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "doodle",
      link: "/product/doodle",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "mix-pose",
      link: "/product/mix-pose",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "create-tile",
      link: "/product/create-tile",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "inpainting",
      link: "/product/inpainting",
    },
    // {
    //   icon: "",
    //   image: "/tools/tool-wrap-1.png",
    //   text: "SDXL-Turbo",
    //   link: "/product/sdxl-turbo",
    // },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "LCM-txt2img",
      link: "/product/lcm-txt2img",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "LCM-img2img",
      link: "/product/lcm-img2img",
    },
  ],
  "AI Image Editor": [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "outpainting",
      link: "/product/outpainting",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "replace-background",
      link: "/product/replace-background",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "replace-sky",
      link: "/product/replace-sky",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "replace-object",
      link: "/product/replace-object",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "remove-background",
      link: "/product/remove-background",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "remove-text",
      link: "/product/remove-text",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "cleanup",
      link: "/product/cleanup",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "remove-watermark",
      link: "/product/remove-watermark",
    },
  ],
  "AI Image Enhancer": [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "upscale",
      link: "/product/upscale",
    },
  ],
  "Face Editor": [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "restore-face",
      link: "/product/restore-face",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "merge-face",
      link: "/product/merge-face",
    },
  ],
  "AI Video Generator": [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "img2video",
      link: "/product/img2video",
    },
    {
      icon: "",
      image: "/tools/tool-wrap-2.png",
      text: "img2video-motion",
      link: "/product/img2video-motion",
    },
  ],
  Training: [
    {
      icon: "",
      image: "/tools/tool-wrap-1.png",
      text: "training",
      link: "/product/training",
    },
  ],
};
const FUNCS: Record<string, FuncData> = {
  FLUX1: {
    name: FUNC_NAME.FLUX1,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.FLUX1,
    docUrl: DOCS_URL.FLUX1,
    getStartedUrl: DOCS_URL.FLUX1,
    playgroundReady: false,
    productpageReady: false,
    cover: "/hub/flux1.png",
    coverAlt: "novita.ai API, Flux1",
    smallIcon: "/header/flux1.png",
    url: DOCS_URL.FLUX1,
  },
  TXT2IMG: {
    name: FUNC_NAME.TXT2IMG,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.TXT2IMG,
    docUrl: DOCS_URL.TXT2IMG,
    getStartedUrl: DOCS_URL.TXT2IMG,
    playgroundReady: true,
    productpageReady: true,
    cover: "/hub/txt2img.png",
    coverAlt: "novita.ai API, Text to Image",
    showcaseVideo: [
      {
        src: "/hub/txt2img.webm",
        type: "video/webm",
      },
      {
        src: "/hub/txt2img.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/txt2img.png",
  },
  IMG2IMG: {
    name: FUNC_NAME.IMG2IMG,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.IMG2IMG,
    docUrl: DOCS_URL.IMG2IMG,
    getStartedUrl: DOCS_URL.IMG2IMG,
    playgroundReady: true,
    productpageReady: true,
    cover: "/hub/img2img.png",
    coverAlt: "novita.ai API, Image to Image",
    showcaseVideo: [
      {
        src: "/hub/img2img.webm",
        type: "video/webm",
      },
      {
        src: "/hub/img2img.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/img2img.png",
  },
  LCM_TXT2IMG: {
    name: FUNC_NAME.LCM_TXT2IMG,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.LCM_TXT2IMG,
    docUrl: DOCS_URL.LCM_TXT2IMG,
    getStartedUrl: DOCS_URL.LCM_TXT2IMG,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/txt2img.png",
  },
  LLM_CHAT: {
    name: FUNC_NAME.LLM_CHAT,
    type: FUNC_TYPE.LLM,
    displayName: FUNC_DISPLAY_NAME.LLM_CHAT,
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2speech.png",
    url: "/llm-api",
  },
  LCM_IMG2IMG: {
    name: FUNC_NAME.LCM_IMG2IMG,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.LCM_IMG2IMG,
    // docUrl: DOCS_URL.LCM_IMG2IMG,
    // getStartedUrl: DOCS_URL.LCM_IMG2IMG,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/lcm-img2img.png",
  },
  UPSCALE: {
    name: FUNC_NAME.UPSCALE,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.UPSCALE,
    docUrl: DOCS_URL.UPSCALE,
    getStartedUrl: DOCS_URL.UPSCALE,
    playgroundReady: false,
    productpageReady: false,
    cover: "/hub/Upscale.png",
    coverAlt: "novita.ai API, Upscale",
    smallIcon: "/header/upscale.png",
  },
  REMOVE_BACKGROUND: {
    name: FUNC_NAME.REMOVE_BACKGROUND,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REMOVE_BACKGROUND,
    docUrl: DOCS_URL.REMOVE_BACKGROUND,
    getStartedUrl: DOCS_URL.REMOVE_BACKGROUND,
    playgroundReady: true,
    productpageReady: true,
    cover: "/hub/Removebg.jpeg",
    coverAlt: "novita.ai API, Remove Background",
    smallIcon: "/header/remove-background.png",
  },
  REPLACE_BACKGROUND: {
    name: FUNC_NAME.REPLACE_BACKGROUND,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REPLACE_BACKGROUND,
    docUrl: DOCS_URL.REPLACE_BACKGROUND,
    getStartedUrl: DOCS_URL.REPLACE_BACKGROUND,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/replace-background.png",
  },
  OUTPAINTING: {
    name: FUNC_NAME.OUTPAINTING,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.OUTPAINTING,
    docUrl: DOCS_URL.OUTPAINTING,
    getStartedUrl: DOCS_URL.OUTPAINTING,
    playgroundReady: false,
    productpageReady: false,
    cover: "/hub/outpainting.png",
    coverAlt: "novita.ai API, more",
    showcaseVideo: [
      {
        src: "/hub/Outpainting.webm",
        type: "video/webm",
      },
      {
        src: "/hub/Outpainting.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/outpainting.png",
  },
  INPAINTING: {
    name: FUNC_NAME.INPAINTING,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.INPAINTING,
    docUrl: DOCS_URL.INPAINTING,
    getStartedUrl: DOCS_URL.INPAINTING,
    playgroundReady: true,
    productpageReady: true,
    cover: "/hub/inpainting.png",
    coverAlt: "novita.ai API, Inpainting",
    showcaseVideo: [
      {
        src: "/hub/inpainting.webm",
        type: "video/webm",
      },
      {
        src: "/hub/inpainting.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/inpainting.png",
  },
  MIX_POSE: {
    name: FUNC_NAME.MIX_POSE,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.MIX_POSE,
    docUrl: DOCS_URL.MIX_POSE,
    getStartedUrl: DOCS_URL.MIX_POSE,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/mix-pose.png",
  },
  DOODLE: {
    name: FUNC_NAME.DOODLE,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.DOODLE,
    docUrl: DOCS_URL.DOODLE,
    getStartedUrl: DOCS_URL.DOODLE,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/doodle.png",
  },
  MERGE_FACE: {
    name: FUNC_NAME.MERGE_FACE,
    type: FUNC_TYPE.FACE_EDITOR,
    displayName: FUNC_DISPLAY_NAME.MERGE_FACE,
    docUrl: DOCS_URL.MERGE_FACE,
    getStartedUrl: DOCS_URL.MERGE_FACE,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/merge-face.png",
  },
  FaceFusion: {
    name: FUNC_NAME.FACEFUSION,
    type: FUNC_TYPE.FACE_EDITOR,
    displayName: FUNC_DISPLAY_NAME.Facefusion,
    docUrl: DOCS_URL.Facefusion,
    getStartedUrl: DOCS_URL.Facefusion,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/merge-face.png",
    url: DOCS_URL.Facefusion,
  },
  REPLACE_SKY: {
    name: FUNC_NAME.REPLACE_SKY,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REPLACE_SKY,
    docUrl: DOCS_URL.REPLACE_SKY,
    getStartedUrl: DOCS_URL.REPLACE_SKY,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/replace-sky.png",
  },
  REPLACE_OBJECT: {
    name: FUNC_NAME.REPLACE_OBJECT,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REPLACE_OBJECT,
    docUrl: DOCS_URL.REPLACE_OBJECT,
    getStartedUrl: DOCS_URL.REPLACE_OBJECT,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/replace-object.png",
  },
  REMOVE_TEXT: {
    name: FUNC_NAME.REMOVE_TEXT,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REMOVE_TEXT,
    docUrl: DOCS_URL.REMOVE_TEXT,
    getStartedUrl: DOCS_URL.REMOVE_TEXT,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/remove-text.png",
  },
  RESTORE_FACE: {
    name: FUNC_NAME.RESTORE_FACE,
    type: FUNC_TYPE.FACE_EDITOR,
    displayName: FUNC_DISPLAY_NAME.RESTORE_FACE,
    docUrl: DOCS_URL.RESTORE_FACE,
    getStartedUrl: DOCS_URL.RESTORE_FACE,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/restore-face.png",
  },
  MAKE_PHOTO: {
    name: FUNC_NAME.MAKE_PHOTO,
    type: FUNC_TYPE.FACE_EDITOR,
    displayName: FUNC_DISPLAY_NAME.MAKE_PHOTO,
    docUrl: DOCS_URL.MAKE_PHOTO,
    getStartedUrl: DOCS_URL.MAKE_PHOTO,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/restore-face.png",
    url: DOCS_URL.MAKE_PHOTO,
  },
  REMOVE_WATERMARK: {
    name: FUNC_NAME.REMOVE_WATERMARK,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.REMOVE_WATERMARK,
    docUrl: DOCS_URL.REMOVE_WATERMARK,
    getStartedUrl: DOCS_URL.REMOVE_WATERMARK,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/remove-text.png",
  },
  CLEANUP: {
    name: FUNC_NAME.CLEANUP,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.CLEANUP,
    docUrl: DOCS_URL.CLEANUP,
    getStartedUrl: DOCS_URL.CLEANUP,
    playgroundReady: true,
    productpageReady: true,
    cover: "/hub/Cleanup.png",
    coverAlt: "novita.ai API, Cleanup",
    smallIcon: "/header/cleanup.png",
  },
  TILE: {
    name: FUNC_NAME.TILE,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.TILE,
    docUrl: DOCS_URL.TILE,
    getStartedUrl: DOCS_URL.TILE,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/create-tile.png",
  },
  REIMAGINE: {
    name: FUNC_NAME.REIMAGINE,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.REIMAGINE,
    docUrl: DOCS_URL.REIMAGINE,
    getStartedUrl: DOCS_URL.REIMAGINE,
    playgroundReady: false,
    productpageReady: false,
    cover: "/hub/reimage.png",
    coverAlt: "novita.ai API, Reimage",
    showcaseVideo: [
      {
        src: "/hub/Reimage.webm",
        type: "video/webm",
      },
      {
        src: "/hub/Reimage.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/reimagine.png",
  },
  SDXL: {
    name: FUNC_NAME.SDXL,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.SDXL,
    docUrl: DOCS_URL.SDXL,
    getStartedUrl: DOCS_URL.SDXL,
    playgroundReady: true,
    productpageReady: false,
    cover: "/hub/SDXL.png",
    coverAlt: "novita.ai API, SDXL",
    showcaseVideo: [
      {
        src: "/hub/SDXL.webm",
        type: "video/webm",
      },
      {
        src: "/hub/SDXL.mp4",
        type: "video/mp4",
      },
    ],
    smallIcon: "/header/txt2img.png",
  },
  WAN_T2V: {
    name: FUNC_NAME.WAN_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.WAN_T2V,
    docUrl: DOCS_URL.WAN_T2V,
    getStartedUrl: DOCS_URL.WAN_T2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  WAN_I2V: {
    name: FUNC_NAME.WAN_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.WAN_I2V,
    docUrl: DOCS_URL.WAN_I2V,
    getStartedUrl: DOCS_URL.WAN_I2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  WAN_2_6_T2V: {
    name: FUNC_NAME.WAN_2_6_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Wan 2.6 Text to Video",
    docUrl: DOCS_URL.WAN_2_6_T2V,
    getStartedUrl: DOCS_URL.WAN_2_6_T2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  WAN_2_6_I2V: {
    name: FUNC_NAME.WAN_2_6_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Wan 2.6 Image to Video",
    docUrl: DOCS_URL.WAN_2_6_I2V,
    getStartedUrl: DOCS_URL.WAN_2_6_I2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  WAN_2_6_V2V: {
    name: FUNC_NAME.WAN_2_6_V2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Wan 2.6 Reference to Video",
    docUrl: DOCS_URL.WAN_2_6_V2V,
    getStartedUrl: DOCS_URL.WAN_2_6_V2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  HUNYUAN_VIDEO_FAST: {
    name: FUNC_NAME.HUNYUAN_VIDEO_FAST,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.HUNYUAN_VIDEO_FAST,
    docUrl: DOCS_URL.HUNYUAN_VIDEO_FAST,
    getStartedUrl: DOCS_URL.HUNYUAN_VIDEO_FAST,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V1_6_T2V: {
    name: FUNC_NAME.KLING_V1_6_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME["KLING_V1.6_T2V"],
    docUrl: DOCS_URL.KLING_V1_6_T2V,
    getStartedUrl: DOCS_URL.KLING_V1_6_T2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V1_6_I2V: {
    name: FUNC_NAME.KLING_V1_6_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME["KLING_V1.6_I2V"],
    docUrl: DOCS_URL.KLING_V1_6_I2V,
    getStartedUrl: DOCS_URL.KLING_V1_6_I2V,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V2_5_T2V: {
    name: FUNC_NAME.KLING_V2_5_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling V2.5 Turbo Text to Video",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V2_5_I2V: {
    name: FUNC_NAME.KLING_V2_5_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling V2.5 Turbo Image to Video",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V26_PRO_MOTION_CONTROL: {
    name: FUNC_NAME.KLING_V26_PRO_MOTION_CONTROL,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling V2.6 Pro Motion Control",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V26_PRO_T2V: {
    name: FUNC_NAME.KLING_V26_PRO_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling V2.6 Pro Text to Video",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V26_PRO_I2V: {
    name: FUNC_NAME.KLING_V26_PRO_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling V2.6 Pro Image to Video",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V30_STD_T2V: {
    name: FUNC_NAME.KLING_V30_STD_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling v3.0 Standard Text-to-Video",
    docUrl: DOCS_URL.KLING_V30_STD_T2V,
    getStartedUrl: DOCS_URL.KLING_V30_STD_T2V,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V30_STD_I2V: {
    name: FUNC_NAME.KLING_V30_STD_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling v3.0 Standard Image-to-Video",
    docUrl: DOCS_URL.KLING_V30_STD_I2V,
    getStartedUrl: DOCS_URL.KLING_V30_STD_I2V,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V30_PRO_T2V: {
    name: FUNC_NAME.KLING_V30_PRO_T2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling v3.0 Pro Text-to-Video",
    docUrl: DOCS_URL.KLING_V30_PRO_T2V,
    getStartedUrl: DOCS_URL.KLING_V30_PRO_T2V,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  KLING_V30_PRO_I2V: {
    name: FUNC_NAME.KLING_V30_PRO_I2V,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Kling v3.0 Pro Image-to-Video",
    docUrl: DOCS_URL.KLING_V30_PRO_I2V,
    getStartedUrl: DOCS_URL.KLING_V30_PRO_I2V,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  HEYGEN_VIDEO_TRANSLATE: {
    name: FUNC_NAME.HEYGEN_VIDEO_TRANSLATE,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: "Heygen Video-translate",
    docUrl: "",
    getStartedUrl: "",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  MINIMAX_VIDEO_01: {
    name: FUNC_NAME.MINIMAX_VIDEO_01,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.MINIMAX_VIDEO_01,
    docUrl: DOCS_URL.MINIMAX_VIDEO_01,
    getStartedUrl: DOCS_URL.MINIMAX_VIDEO_01,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  MINIMAX_HAILUO_02: {
    name: FUNC_NAME.MINIMAX_HAILUO_02,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.MINIMAX_HAILUO_02,
    docUrl: DOCS_URL.MINIMAX_HAILUO_02,
    getStartedUrl: DOCS_URL.MINIMAX_HAILUO_02,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  TXT2VIDEO: {
    name: FUNC_NAME.TXT2VIDEO,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.TXT2VIDEO,
    docUrl: DOCS_URL.TXT2VIDEO,
    getStartedUrl: DOCS_URL.TXT2VIDEO,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/txt2video.png",
  },
  IMG2VIDEO: {
    name: FUNC_NAME.IMG2VIDEO,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.IMG2VIDEO,
    docUrl: DOCS_URL.IMG2VIDEO,
    getStartedUrl: DOCS_URL.IMG2VIDEO,
    playgroundReady: true,
    productpageReady: true,
    smallIcon: "/header/img2video.png",
  },
  SDXL_TURBO: {
    name: FUNC_NAME.SDXL_TURBO,
    type: FUNC_TYPE.IMG_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.SDXL_TURBO,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2img.png",
  },
  TRAINING: {
    name: FUNC_NAME.TRAINING,
    type: FUNC_TYPE.TRAINING,
    displayName: FUNC_DISPLAY_NAME.TRAINING,
    docUrl: DOCS_URL.TRAINING,
    getStartedUrl: DOCS_URL.TRAINING,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/training.png",
  },
  MOTIONSYNC: {
    name: FUNC_NAME.MOTIONSYNC,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.MOTIONSYNC,
    docUrl: DOCS_URL.MOTIONSYNC,
    getStartedUrl: DOCS_URL.MOTIONSYNC,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2video-motion.png",
  },
  ANIMATE_ANYONE: {
    name: FUNC_NAME.ANIMATE_ANYONE,
    type: FUNC_TYPE.VIDEO_GENERATOR,
    displayName: FUNC_DISPLAY_NAME.ANIMATE_ANYONE,
    docUrl: DOCS_URL.ANIMATE_ANYONE,
    getStartedUrl: DOCS_URL.ANIMATE_ANYONE,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2video-motion.png",
  },
  // VIDEO_REMOVE_SUBTITLE: {
  //   name: FUNC_NAME.VIDEO_REMOVE_SUBTITLE,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_REMOVE_SUBTITLE,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-remove-subtitle.png",
  // },
  // VIDEO_REMOVE_WATERMARK: {
  //   name: FUNC_NAME.VIDEO_REMOVE_WATERMARK,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_REMOVE_WATERMARK,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-remove-watermark.png",
  // },
  // VIDEO_TRANSLATE: {
  //   name: FUNC_NAME.VIDEO_TRANSLATE,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_TRANSLATE,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-translate.png",
  // },
  // VIDEO_REMOVE_OBJECT: {
  //   name: FUNC_NAME.VIDEO_REMOVE_OBJECT,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_REMOVE_OBJECT,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-remove-object.png",
  // },
  VIDEO_MERGE_FACE: {
    name: FUNC_NAME.VIDEO_MERGE_FACE,
    type: FUNC_TYPE.FACE_EDITOR,
    displayName: FUNC_DISPLAY_NAME.VIDEO_MERGE_FACE,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/video-merge-face.png",
    docUrl: DOCS_URL.VIDEO_MERGE_FACE,
    url: DOCS_URL.VIDEO_MERGE_FACE,
  },
  // VIDEO_UPSCALE: {
  //   name: FUNC_NAME.VIDEO_UPSCALE,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_UPSCALE,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-upscale.png",
  // },
  // VIDEO_MAGIC_CUT: {
  //   name: FUNC_NAME.VIDEO_MAGIC_CUT,
  //   type: FUNC_TYPE.VIDEO_EDITOR,
  //   displayName: FUNC_DISPLAY_NAME.VIDEO_MAGIC_CUT,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/video-magic-cut.png",
  // },
  // SPEECH2TXT: {
  //   name: FUNC_NAME.SPEECH2TXT,
  //   type: FUNC_TYPE.AUDIO,
  //   displayName: FUNC_DISPLAY_NAME.SPEECH2TXT,
  //   docUrl: DOCS_URL.SPEECH2TXT,
  //   getStartedUrl: DOCS_URL.SPEECH2TXT,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/speech2txt-transcription.png",
  // },
  // SPEECH2_TXT_TRANSLATION: {
  //   name: FUNC_NAME.SPEECH2TXT_TRANSLATE,
  //   type: FUNC_TYPE.AUDIO,
  //   displayName: FUNC_DISPLAY_NAME.SPEECH2TXT_TRANSLATE,
  //   docUrl: DOCS_URL.SPEECH2TXT_TRANSLATION,
  //   getStartedUrl: DOCS_URL.SPEECH2TXT_TRANSLATION,
  //   playgroundReady: false,
  //   productpageReady: true,
  //   smallIcon: "/header/speech2txt-translation.png",
  // },
  TXT2SPEECH: {
    name: FUNC_NAME.TXT2SPEECH,
    type: FUNC_TYPE.AUDIO,
    displayName: FUNC_DISPLAY_NAME.TXT2SPEECH,
    docUrl: DOCS_URL.TXT2SPEECH,
    getStartedUrl: DOCS_URL.TXT2SPEECH,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/txt2speech.png",
  },
  VOICE_CLONING_INSTANT: {
    name: FUNC_NAME.VOICE_CLONING_INSTANT,
    type: FUNC_TYPE.AUDIO,
    displayName: FUNC_DISPLAY_NAME.VOICE_CLONING_INSTANT,
    docUrl: DOCS_URL.VOICE_CLONING_INSTANT,
    getStartedUrl: DOCS_URL.VOICE_CLONING_INSTANT,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/voice-cloning-instant.png",
  },
  VOICE_CLONING: {
    name: FUNC_NAME.VOICE_CLONING,
    type: FUNC_TYPE.AUDIO,
    displayName: FUNC_DISPLAY_NAME.VOICE_CLONING,
    docUrl: DOCS_URL.VOICE_CLONING,
    getStartedUrl: DOCS_URL.VOICE_CLONING,
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/voice-cloning.png",
  },
  IMG2MASK: {
    name: FUNC_NAME.IMG2MASK,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.IMG2MASK,
    docUrl: DOCS_URL.IMG2MASK,
    getStartedUrl: DOCS_URL.IMG2MASK,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2img.png",
    url: DOCS_URL.IMG2MASK,
  },
  IMG2PROMPT: {
    name: FUNC_NAME.IMG2PROMPT,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.IMG2PROMPT,
    docUrl: DOCS_URL.IMG2PROMPT,
    getStartedUrl: DOCS_URL.IMG2PROMPT,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/txt2speech.png",
    url: DOCS_URL.IMG2PROMPT,
  },
  ADETAILER: {
    name: FUNC_NAME.ADETAILER,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.ADETAILER,
    docUrl: DOCS_URL.ADETAILER,
    getStartedUrl: DOCS_URL.ADETAILER,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2img.png",
    url: DOCS_URL.ADETAILER,
  },
  RELIGHT: {
    name: FUNC_NAME.RELIGHT,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: FUNC_DISPLAY_NAME.RELIGHT,
    docUrl: DOCS_URL.RELIGHT,
    getStartedUrl: DOCS_URL.RELIGHT,
    playgroundReady: false,
    productpageReady: false,
    smallIcon: "/header/img2img.png",
    url: DOCS_URL.RELIGHT,
  },
  IMAGE_REMOVE_BACKGROUND: {
    name: FUNC_NAME.IMAGE_REMOVE_BACKGROUND,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: "Image Remove Background",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/remove-background.png",
  },
  IMAGE_ERASER: {
    name: FUNC_NAME.IMAGE_ERASER,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: "Image Eraser",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/img2img.png",
  },
  IMAGE_UPSCALER: {
    name: FUNC_NAME.IMAGE_UPSCALER,
    type: FUNC_TYPE.IMG_EDITOR,
    displayName: "Image Upscaler",
    playgroundReady: false,
    productpageReady: true,
    smallIcon: "/header/upscale.png",
  },
};
export default FUNCS;
