import type { AnchorHTMLAttributes, ReactNode } from "react";
import { fireEvent, render, screen } from "@testing-library/react";

jest.mock("react-redux", () => ({
  useSelector: jest.fn(),
}));

jest.mock("next/link", () => {
  const MockNextLink = ({
    children,
    href,
    ...props
  }: AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string;
    children: ReactNode;
  }) => (
    <a href={href} {...props}>
      {children}
    </a>
  );

  MockNextLink.displayName = "MockNextLink";

  return MockNextLink;
});

jest.mock("next/image", () => {
  const MockNextImage = ({
    alt,
    src,
    className,
    fill: _fill,
    priority: _priority,
    sizes: _sizes,
    ...props
  }: {
    alt: string;
    src: string;
    className?: string;
    fill?: boolean;
    priority?: boolean;
    sizes?: string;
  }) => <img alt={alt} src={src} className={className} {...props} />;

  MockNextImage.displayName = "MockNextImage";

  return MockNextImage;
});

jest.mock("@/app/components/button/Button", () => {
  const MockButton = ({
    children,
    className,
    link,
    renderTag,
    elAttrs,
    ...props
  }: {
    children: ReactNode;
    className?: string;
    link?: string;
    renderTag?: "button" | "link";
    elAttrs?: Record<string, string>;
  }) =>
    renderTag === "link" ? (
      <a
        href={link}
        className={className}
        data-testid="mock-button"
        {...elAttrs}
        {...props}
      >
        {children}
      </a>
    ) : (
      <button className={className} data-testid="mock-button" {...props}>
        {children}
      </button>
    );

  MockButton.displayName = "MockButton";

  return MockButton;
});

jest.mock("@/i18n/provider", () => ({
  useI18n: jest.fn(),
}));

import { HomeCampaignBanner } from "@/app/components/campaigns/HomeCampaignBanner";
import { useI18n } from "@/i18n/provider";

const { useSelector } = jest.requireMock("react-redux") as {
  useSelector: jest.Mock;
};

const buildItem = (overrides: Record<string, string> = {}) => ({
  badgeText: "AI-Powered Generation",
  buttonHref: "/coding-plan",
  buttonText: "View Details",
  // i18n-disable-next-line
  description:
    "Explore thousands of apps generated by the community. Fork, remix, and display in seconds. The future of creation is here.",
  headingPart1: "Generate anything,",
  headingPart2: "Share the magic.",
  ...overrides,
});

const renderBanner = () => render(<HomeCampaignBanner />);

describe("HomeCampaignBanner", () => {
  beforeEach(() => {
    (useI18n as jest.Mock).mockReturnValue({
      locale: "en",
    });
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it("renders null when there are no homepage campaign items", () => {
    useSelector.mockImplementation((selector) =>
      selector({
        config: {
          campaignConfig: {
            homeCampaignBanner: [],
          },
        },
      }),
    );

    const { container } = renderBanner();

    expect(container.firstChild).toBeNull();
  });

  it("renders a single banner item without pager and localizes internal CTA href", () => {
    useSelector.mockImplementation((selector) =>
      selector({
        config: {
          campaignConfig: {
            homeCampaignBanner: [buildItem()],
          },
        },
      }),
    );

    const { container } = renderBanner();

    expect(screen.getByText("AI-Powered Generation")).toBeInTheDocument();
    expect(screen.getByText("Generate anything,")).toBeInTheDocument();
    expect(screen.getByText("Share the magic.")).toBeInTheDocument();
    expect(screen.queryByLabelText("Previous banner")).not.toBeInTheDocument();
    expect(screen.getByTestId("mock-button")).toHaveAttribute(
      "href",
      "/coding-plan",
    );
    expect(screen.queryByText("›")).not.toBeInTheDocument();
    expect(container.querySelector(".sectionShell")).toBeInTheDocument();
    expect(container.querySelectorAll("img")).toHaveLength(1);
    expect(container.querySelector(".backgroundImage")).toBeInTheDocument();
  });

  it("renders pager for multiple items and switches content without turning the title into a link", () => {
    useSelector.mockImplementation((selector) =>
      selector({
        config: {
          campaignConfig: {
            homeCampaignBanner: [
              buildItem(),
              buildItem({
                badgeText: "Hackathon",
                buttonHref: "https://renderarena.novita.ai/api/auth/callback",
                headingPart1: "Multiple models.",
                headingPart2: "Live battles.",
                // i18n-disable-next-line
                description:
                  "Test how different models render the same idea — compare, judge, and share in real time.",
              }),
            ],
          },
        },
      }),
    );

    renderBanner();

    expect(screen.getByText("1 / 2")).toBeInTheDocument();
    expect(screen.queryByText("<")).not.toBeInTheDocument();
    expect(screen.queryByText(">")).not.toBeInTheDocument();
    expect(screen.getByText("Generate anything,").closest("a")).toBeNull();
    expect(screen.getByTestId("mock-button")).toHaveTextContent("View Details");

    fireEvent.click(screen.getByLabelText("Next banner"));

    expect(screen.getByText("2 / 2")).toBeInTheDocument();
    expect(screen.getByText("Hackathon")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /view details/i })).toHaveAttribute(
      "href",
      "https://renderarena.novita.ai/api/auth/callback",
    );
  });

  it("preserves the full heading while only the right title segment is marked for truncation", () => {
    const headingPart1 =
      "Build and launch agent workflows across every model provider with unified billing";
    const headingPart2 =
      "without rebuilding your integration every time your roadmap changes";

    useSelector.mockImplementation((selector) =>
      selector({
        config: {
          campaignConfig: {
            homeCampaignBanner: [
              buildItem({
                headingPart1,
                headingPart2,
              }),
            ],
          },
        },
      }),
    );

    renderBanner();

    expect(screen.getByRole("heading", { level: 2 })).toHaveAttribute(
      "title",
      `${headingPart1} ${headingPart2}`,
    );
    expect(screen.getByText(headingPart1)).not.toHaveAttribute("title");
    expect(screen.getByText(headingPart2)).toHaveAttribute(
      "title",
      headingPart2,
    );
  });
});
