import { NOVITA_URL } from "./constants/urls";

export const urlMap: Record<string, string> = {
  "/api-catalogue": NOVITA_URL.MODEL_LIBRARY_INDEX,
  "/model-api/api-catalogue": NOVITA_URL.MODEL_LIBRARY_INDEX,
  "/chat-completion": NOVITA_URL.LLM_PAGE,
  "/llm-api": NOVITA_URL.LLM_PAGE,
  "/model-api/llm-api": NOVITA_URL.LLM_PAGE,
  "/model-api/product/llm-api": NOVITA_URL.LLM_PAGE,
  "/model": NOVITA_URL.MODEL_LIBRARY_INDEX,
  "/model-api/model": NOVITA_URL.MODEL_LIBRARY_INDEX,
  "/model/upload": NOVITA_URL.MODEL_API_CONSOLE_MODEL,
  "/model-api/model/upload": NOVITA_URL.MODEL_API_CONSOLE_MODEL,
  "/model/:id": "/model-api/model/:id", // seo page
  "/model-api/product/llm-api/playground/:id": "/models/llm/:id",
  "/llm/:id": "/models/llm/:id",
  "/llm-api/playground": NOVITA_URL.MODEL_API_LLM_PLAYGROUND,
  "/model-api/product/llm-api/playground": NOVITA_URL.MODEL_API_LLM_PLAYGROUND,
  "/model-api/llm-api/playground": NOVITA_URL.MODEL_API_LLM_PLAYGROUND,
  "/model-api/console": NOVITA_URL.MODEL_API_CONSOLE,
  "/model-api/legal/privacy-policy": NOVITA_URL.PRIVACY_POLICY,
  "/model-api/legal/terms-of-service": NOVITA_URL.TERMS_OF_SERVICE,
  "/model-api/legal/enterprise-plan-sla": NOVITA_URL.DEDICATED_ENDPOINTS_SLA,
  "/model-api/console/enterprise": NOVITA_URL.MODEL_API_CONSOLE_IMAGE_DE,
  "/models-console/dedicated-endpoints": NOVITA_URL.MODEL_API_CONSOLE_IMAGE_DE,
  "/legal/enterprise-plan-sla": NOVITA_URL.DEDICATED_ENDPOINTS_SLA,
  "/image/pokemon/:id": "/model-api/image/pokemon/:id", // seo page
  "/image/:id": "/model-api/image/:id", // seo page
  "/model-api/order": NOVITA_URL.DEDICATED_ENDPOINT_ORDER,
  "/order": NOVITA_URL.DEDICATED_ENDPOINT_ORDER,
  "/playground": NOVITA_URL.MODEL_API_PLAYGROUND,
  "/model-api/playground": NOVITA_URL.MODEL_API_PLAYGROUND,
  "/product/video-remove-subtitle": NOVITA_URL.HOME,
  "/product/video-remove-watermark": NOVITA_URL.HOME,
  "/product/video-upscale": NOVITA_URL.HOME,
  "/product/video-translate": NOVITA_URL.HOME,
  "/product/video-magic-cut": NOVITA_URL.HOME,
  "/product/video-remove-object": NOVITA_URL.HOME,
  "/product/video-merge-face": NOVITA_URL.HOME,
  "/product/speech2txt-translate": NOVITA_URL.HOME,
  "/product/speech2txt": NOVITA_URL.HOME,
  "/model-api/product/video-remove-subtitle": NOVITA_URL.HOME,
  "/model-api/product/video-remove-watermark": NOVITA_URL.HOME,
  "/model-api/product/video-upscale": NOVITA_URL.HOME,
  "/model-api/product/video-translate": NOVITA_URL.HOME,
  "/model-api/product/video-magic-cut": NOVITA_URL.HOME,
  "/model-api/product/video-remove-object": NOVITA_URL.HOME,
  "/model-api/product/video-merge-face": NOVITA_URL.HOME,
  "/model-api/product/speech2txt-translate": NOVITA_URL.HOME,
  "/model-api/product/speech2txt": NOVITA_URL.HOME,
  "/model-api/product": NOVITA_URL.MODEL_API_INDEX,
  "/product/:id": "/model-api/product/:id",
  "/dashboard": NOVITA_URL.MODEL_API_CONSOLE,
  "/dashboard/enterprise": NOVITA_URL.MODEL_API_CONSOLE_IMAGE_DE,
  "/dashboard/key": NOVITA_URL.KEYS,
  "/dashboard/billing": NOVITA_URL.BILLING_OVERVIEW,
  "/model-api/dashboard/billing": NOVITA_URL.BILLING_OVERVIEW,
  "/dashboard/setting": NOVITA_URL.MODEL_API_CONSOLE_SETTINGS,
  "/model-api/settings": NOVITA_URL.MODEL_API_CONSOLE_SETTINGS,
  "/gpu-instance/console/explore": NOVITA_URL.GPU_CONSOLE_EXPLORE,
  "/gpu-instance/console/instances": NOVITA_URL.GPU_CONSOLE_INSTANCES,
  "/gpu-instance/console/serverless": NOVITA_URL.GPU_CONSOLE_SERVERLESS,
  "/gpu-instance/console/storage": NOVITA_URL.GPU_CONSOLE_STORAGE,
  "/gpu-instance/console/templates": NOVITA_URL.GPU_CONSOLE_TEMPLATES,
  "/gpu-instance/console/billing": NOVITA_URL.BILLING_DETAILS,
  "/gpu-instance/console/jobs": NOVITA_URL.GPU_CONSOLE_JOBS,
  "/gpu-instance/console/settings": NOVITA_URL.GPU_CONSOLE_SETTINGS,
  "/gpu-instance/console": NOVITA_URL.GPU_CONSOLE_EXPLORE,
  "/model-api/console/llm-metrics": NOVITA_URL.MODEL_API_CONSOLE_LLM_METRICS,
  "/model-api/console/dedicated-endpoints":
    NOVITA_URL.MODEL_API_CONSOLE_IMAGE_DE,
  "/model-api/console/model": NOVITA_URL.MODEL_API_CONSOLE_MODEL,
  "/model-api/console/settings": NOVITA_URL.MODEL_API_CONSOLE_SETTINGS,
  "/model-api/product/txt2speech": NOVITA_URL.MODEL_API_VOICE_PLAYGROUND,
  "/model-api/pricing": NOVITA_URL.PRICING,
  "/gpu-instance/pricing": `${NOVITA_URL.PRICING}?gpu=1`,
  "/model-api/end-of-service": NOVITA_URL.END_OF_SERVICE,
  "/gpu-instance/gpu/:id": NOVITA_URL.GPU_DETAIL,
  "/billing/payment-methods": NOVITA_URL.BILLING_PAYMENT,
  "/billing/billing-transactions": NOVITA_URL.BILLING_TRANSACTIONS,
  "/billing/billing-details": NOVITA_URL.BILLING_DETAILS,
  "/serverless": NOVITA_URL.GPU_INDEX,
  "/gpu-instance": NOVITA_URL.GPU_INDEX,
  "/model-api": NOVITA_URL.MODEL_LIBRARY_INDEX,
  // no account page
  "/legal/return-policy": NOVITA_URL.PRIVACY_POLICY,
  "/account": NOVITA_URL.SETTINGS,
  "/account/key": NOVITA_URL.KEYS,
  "/gpus-console/billing": NOVITA_URL.BILLING_DETAILS,
  "/templates": NOVITA_URL.GPU_CONSOLE_TEMPLATE_LIBRARY,
  "/settings#key-management": NOVITA_URL.KEYS,
  "/quota-limits": NOVITA_URL.QUOTA_LIMITS_LLM,
};
